package game

type FightState struct {
	UserID            uint32
	OpponentUserID    uint32
	PendingSkillID    int
	PlayerLastSkill   int
	EnemyLastSkill    int
	PlayerEncoreSkill int
	PlayerEncoreTurns int
	EnemyEncoreSkill  int
	EnemyEncoreTurns  int
	PlayerBoundTurns  int
	EnemyBoundTurns   int
	PlayerFlinch      bool
	EnemyFlinch       bool
	PlayerPetID       uint32
	PlayerLevel       uint32
	PlayerDV          uint32
	PlayerHP          int
	PlayerMaxHP       int
	PlayerCatch       uint32
	PlayerSkills      []int
	PlayerStats       petStats
	PlayerType        int
	PlayerStage       stageModifiers
	PlayerSkillPP     map[int]int
	EnemyPetID        uint32
	EnemyLevel        uint32
	EnemyDV           uint32
	EnemyHP           int
	EnemyMaxHP        int
	EnemyCatch        uint32
	EnemySkills       []int
	EnemyStats        petStats
	EnemyType         int
	EnemyStage        stageModifiers
	EnemySkillPP      map[int]int
	EnemyRewardID     int
	EnemyRewardNm     string
	EnemyRewardCt     int
	PlayerFatigue     int
	EnemyFatigue      int
	PlayerStatus      map[int]int
	EnemyStatus       map[int]int
	Turn              int
}
