// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "salt", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
	}
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "operator", Type: field.TypeString, Default: ""},
		{Name: "action", Type: field.TypeString, Default: ""},
		{Name: "resource", Type: field.TypeString, Default: ""},
		{Name: "resource_id", Type: field.TypeString, Default: ""},
		{Name: "detail", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
	}
	// ConfigEntriesColumns holds the columns for the "config_entries" table.
	ConfigEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeBytes},
		{Name: "version", Type: field.TypeInt64, Default: 1},
		{Name: "checksum", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ConfigEntriesTable holds the schema information for the "config_entries" table.
	ConfigEntriesTable = &schema.Table{
		Name:       "config_entries",
		Columns:    ConfigEntriesColumns,
		PrimaryKey: []*schema.Column{ConfigEntriesColumns[0]},
	}
	// ConfigVersionsColumns holds the columns for the "config_versions" table.
	ConfigVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString},
		{Name: "version", Type: field.TypeInt64},
		{Name: "value", Type: field.TypeBytes},
		{Name: "checksum", Type: field.TypeString, Default: ""},
		{Name: "operator", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "config_entry_versions", Type: field.TypeInt, Nullable: true},
	}
	// ConfigVersionsTable holds the schema information for the "config_versions" table.
	ConfigVersionsTable = &schema.Table{
		Name:       "config_versions",
		Columns:    ConfigVersionsColumns,
		PrimaryKey: []*schema.Column{ConfigVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "config_versions_config_entries_versions",
				Columns:    []*schema.Column{ConfigVersionsColumns[7]},
				RefColumns: []*schema.Column{ConfigEntriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// GmUsersColumns holds the columns for the "gm_users" table.
	GmUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// GmUsersTable holds the schema information for the "gm_users" table.
	GmUsersTable = &schema.Table{
		Name:       "gm_users",
		Columns:    GmUsersColumns,
		PrimaryKey: []*schema.Column{GmUsersColumns[0]},
	}
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "item_id", Type: field.TypeInt},
		{Name: "count", Type: field.TypeInt, Default: 1},
		{Name: "meta", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "player_id", Type: field.TypeInt},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "items_players_items",
				Columns:    []*schema.Column{ItemsColumns[6]},
				RefColumns: []*schema.Column{PlayersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
	}
	// PetsColumns holds the columns for the "pets" table.
	PetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "species_id", Type: field.TypeInt},
		{Name: "level", Type: field.TypeInt, Default: 1},
		{Name: "exp", Type: field.TypeInt, Default: 0},
		{Name: "hp", Type: field.TypeInt, Default: 0},
		{Name: "catch_time", Type: field.TypeInt64, Default: 0},
		{Name: "dv", Type: field.TypeInt, Default: 31},
		{Name: "nature", Type: field.TypeString, Default: "normal"},
		{Name: "skills", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "player_id", Type: field.TypeInt},
	}
	// PetsTable holds the schema information for the "pets" table.
	PetsTable = &schema.Table{
		Name:       "pets",
		Columns:    PetsColumns,
		PrimaryKey: []*schema.Column{PetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pets_players_pets",
				Columns:    []*schema.Column{PetsColumns[11]},
				RefColumns: []*schema.Column{PlayersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PlayersColumns holds the columns for the "players" table.
	PlayersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nick", Type: field.TypeString},
		{Name: "level", Type: field.TypeInt, Default: 1},
		{Name: "coins", Type: field.TypeInt64, Default: 0},
		{Name: "gold", Type: field.TypeInt64, Default: 0},
		{Name: "map_id", Type: field.TypeInt, Default: 1},
		{Name: "map_type", Type: field.TypeInt, Default: 0},
		{Name: "pos_x", Type: field.TypeInt, Default: 300},
		{Name: "pos_y", Type: field.TypeInt, Default: 300},
		{Name: "last_map_id", Type: field.TypeInt, Default: 1},
		{Name: "color", Type: field.TypeInt64, Default: 6737151},
		{Name: "texture", Type: field.TypeInt64, Default: 1},
		{Name: "energy", Type: field.TypeInt64, Default: 100},
		{Name: "fight_badge", Type: field.TypeInt64, Default: 0},
		{Name: "time_today", Type: field.TypeInt64, Default: 0},
		{Name: "time_limit", Type: field.TypeInt64, Default: 86400},
		{Name: "teacher_id", Type: field.TypeInt64, Default: 0},
		{Name: "student_id", Type: field.TypeInt64, Default: 0},
		{Name: "cur_title", Type: field.TypeInt64, Default: 0},
		{Name: "task_status", Type: field.TypeString, Default: "{}"},
		{Name: "task_bufs", Type: field.TypeString, Default: "{}"},
		{Name: "current_pet_id", Type: field.TypeInt64, Default: 0},
		{Name: "current_pet_catch_time", Type: field.TypeInt64, Default: 0},
		{Name: "current_pet_dv", Type: field.TypeInt64, Default: 31},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeInt},
	}
	// PlayersTable holds the schema information for the "players" table.
	PlayersTable = &schema.Table{
		Name:       "players",
		Columns:    PlayersColumns,
		PrimaryKey: []*schema.Column{PlayersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "players_accounts_players",
				Columns:    []*schema.Column{PlayersColumns[27]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeInt},
		{Name: "permission_id", Type: field.TypeInt},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0], RolePermissionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_role_id",
				Columns:    []*schema.Column{RolePermissionsColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_permissions_permission_id",
				Columns:    []*schema.Column{RolePermissionsColumns[1]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// RoleGmUsersColumns holds the columns for the "role_gm_users" table.
	RoleGmUsersColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeInt},
		{Name: "gm_user_id", Type: field.TypeInt},
	}
	// RoleGmUsersTable holds the schema information for the "role_gm_users" table.
	RoleGmUsersTable = &schema.Table{
		Name:       "role_gm_users",
		Columns:    RoleGmUsersColumns,
		PrimaryKey: []*schema.Column{RoleGmUsersColumns[0], RoleGmUsersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_gm_users_role_id",
				Columns:    []*schema.Column{RoleGmUsersColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_gm_users_gm_user_id",
				Columns:    []*schema.Column{RoleGmUsersColumns[1]},
				RefColumns: []*schema.Column{GmUsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		AuditLogsTable,
		ConfigEntriesTable,
		ConfigVersionsTable,
		GmUsersTable,
		ItemsTable,
		PermissionsTable,
		PetsTable,
		PlayersTable,
		RolesTable,
		RolePermissionsTable,
		RoleGmUsersTable,
	}
)

func init() {
	ConfigVersionsTable.ForeignKeys[0].RefTable = ConfigEntriesTable
	ItemsTable.ForeignKeys[0].RefTable = PlayersTable
	PetsTable.ForeignKeys[0].RefTable = PlayersTable
	PlayersTable.ForeignKeys[0].RefTable = AccountsTable
	RolePermissionsTable.ForeignKeys[0].RefTable = RolesTable
	RolePermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
	RoleGmUsersTable.ForeignKeys[0].RefTable = RolesTable
	RoleGmUsersTable.ForeignKeys[1].RefTable = GmUsersTable
}
