// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jseer/ent/configentry"
	"jseer/ent/configversion"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConfigVersionCreate is the builder for creating a ConfigVersion entity.
type ConfigVersionCreate struct {
	config
	mutation *ConfigVersionMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *ConfigVersionCreate) SetKey(v string) *ConfigVersionCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ConfigVersionCreate) SetVersion(v int64) *ConfigVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *ConfigVersionCreate) SetValue(v []byte) *ConfigVersionCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *ConfigVersionCreate) SetChecksum(v string) *ConfigVersionCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_c *ConfigVersionCreate) SetNillableChecksum(v *string) *ConfigVersionCreate {
	if v != nil {
		_c.SetChecksum(*v)
	}
	return _c
}

// SetOperator sets the "operator" field.
func (_c *ConfigVersionCreate) SetOperator(v string) *ConfigVersionCreate {
	_c.mutation.SetOperator(v)
	return _c
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_c *ConfigVersionCreate) SetNillableOperator(v *string) *ConfigVersionCreate {
	if v != nil {
		_c.SetOperator(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConfigVersionCreate) SetCreatedAt(v time.Time) *ConfigVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConfigVersionCreate) SetNillableCreatedAt(v *time.Time) *ConfigVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetEntryID sets the "entry" edge to the ConfigEntry entity by ID.
func (_c *ConfigVersionCreate) SetEntryID(id int) *ConfigVersionCreate {
	_c.mutation.SetEntryID(id)
	return _c
}

// SetNillableEntryID sets the "entry" edge to the ConfigEntry entity by ID if the given value is not nil.
func (_c *ConfigVersionCreate) SetNillableEntryID(id *int) *ConfigVersionCreate {
	if id != nil {
		_c = _c.SetEntryID(*id)
	}
	return _c
}

// SetEntry sets the "entry" edge to the ConfigEntry entity.
func (_c *ConfigVersionCreate) SetEntry(v *ConfigEntry) *ConfigVersionCreate {
	return _c.SetEntryID(v.ID)
}

// Mutation returns the ConfigVersionMutation object of the builder.
func (_c *ConfigVersionCreate) Mutation() *ConfigVersionMutation {
	return _c.mutation
}

// Save creates the ConfigVersion in the database.
func (_c *ConfigVersionCreate) Save(ctx context.Context) (*ConfigVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConfigVersionCreate) SaveX(ctx context.Context) *ConfigVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfigVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfigVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConfigVersionCreate) defaults() {
	if _, ok := _c.mutation.Checksum(); !ok {
		v := configversion.DefaultChecksum
		_c.mutation.SetChecksum(v)
	}
	if _, ok := _c.mutation.Operator(); !ok {
		v := configversion.DefaultOperator
		_c.mutation.SetOperator(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := configversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConfigVersionCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "ConfigVersion.key"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ConfigVersion.version"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "ConfigVersion.value"`)}
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		return &ValidationError{Name: "checksum", err: errors.New(`ent: missing required field "ConfigVersion.checksum"`)}
	}
	if _, ok := _c.mutation.Operator(); !ok {
		return &ValidationError{Name: "operator", err: errors.New(`ent: missing required field "ConfigVersion.operator"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ConfigVersion.created_at"`)}
	}
	return nil
}

func (_c *ConfigVersionCreate) sqlSave(ctx context.Context) (*ConfigVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConfigVersionCreate) createSpec() (*ConfigVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &ConfigVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(configversion.Table, sqlgraph.NewFieldSpec(configversion.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(configversion.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(configversion.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(configversion.FieldValue, field.TypeBytes, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(configversion.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.Operator(); ok {
		_spec.SetField(configversion.FieldOperator, field.TypeString, value)
		_node.Operator = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(configversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configversion.EntryTable,
			Columns: []string{configversion.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.config_entry_versions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConfigVersionCreateBulk is the builder for creating many ConfigVersion entities in bulk.
type ConfigVersionCreateBulk struct {
	config
	err      error
	builders []*ConfigVersionCreate
}

// Save creates the ConfigVersion entities in the database.
func (_c *ConfigVersionCreateBulk) Save(ctx context.Context) ([]*ConfigVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConfigVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConfigVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConfigVersionCreateBulk) SaveX(ctx context.Context) []*ConfigVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfigVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfigVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
