// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"jseer/ent/configentry"
	"jseer/ent/configversion"
	"jseer/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConfigVersionQuery is the builder for querying ConfigVersion entities.
type ConfigVersionQuery struct {
	config
	ctx        *QueryContext
	order      []configversion.OrderOption
	inters     []Interceptor
	predicates []predicate.ConfigVersion
	withEntry  *ConfigEntryQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ConfigVersionQuery builder.
func (_q *ConfigVersionQuery) Where(ps ...predicate.ConfigVersion) *ConfigVersionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ConfigVersionQuery) Limit(limit int) *ConfigVersionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ConfigVersionQuery) Offset(offset int) *ConfigVersionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ConfigVersionQuery) Unique(unique bool) *ConfigVersionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ConfigVersionQuery) Order(o ...configversion.OrderOption) *ConfigVersionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEntry chains the current query on the "entry" edge.
func (_q *ConfigVersionQuery) QueryEntry() *ConfigEntryQuery {
	query := (&ConfigEntryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(configversion.Table, configversion.FieldID, selector),
			sqlgraph.To(configentry.Table, configentry.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, configversion.EntryTable, configversion.EntryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ConfigVersion entity from the query.
// Returns a *NotFoundError when no ConfigVersion was found.
func (_q *ConfigVersionQuery) First(ctx context.Context) (*ConfigVersion, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{configversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ConfigVersionQuery) FirstX(ctx context.Context) *ConfigVersion {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ConfigVersion ID from the query.
// Returns a *NotFoundError when no ConfigVersion ID was found.
func (_q *ConfigVersionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{configversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ConfigVersionQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ConfigVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ConfigVersion entity is found.
// Returns a *NotFoundError when no ConfigVersion entities are found.
func (_q *ConfigVersionQuery) Only(ctx context.Context) (*ConfigVersion, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{configversion.Label}
	default:
		return nil, &NotSingularError{configversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ConfigVersionQuery) OnlyX(ctx context.Context) *ConfigVersion {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ConfigVersion ID in the query.
// Returns a *NotSingularError when more than one ConfigVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ConfigVersionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{configversion.Label}
	default:
		err = &NotSingularError{configversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ConfigVersionQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ConfigVersions.
func (_q *ConfigVersionQuery) All(ctx context.Context) ([]*ConfigVersion, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ConfigVersion, *ConfigVersionQuery]()
	return withInterceptors[[]*ConfigVersion](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ConfigVersionQuery) AllX(ctx context.Context) []*ConfigVersion {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ConfigVersion IDs.
func (_q *ConfigVersionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(configversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ConfigVersionQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ConfigVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ConfigVersionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ConfigVersionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ConfigVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ConfigVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ConfigVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ConfigVersionQuery) Clone() *ConfigVersionQuery {
	if _q == nil {
		return nil
	}
	return &ConfigVersionQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]configversion.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.ConfigVersion{}, _q.predicates...),
		withEntry:  _q.withEntry.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEntry tells the query-builder to eager-load the nodes that are connected to
// the "entry" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ConfigVersionQuery) WithEntry(opts ...func(*ConfigEntryQuery)) *ConfigVersionQuery {
	query := (&ConfigEntryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEntry = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ConfigVersion.Query().
//		GroupBy(configversion.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ConfigVersionQuery) GroupBy(field string, fields ...string) *ConfigVersionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ConfigVersionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = configversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	client.ConfigVersion.Query().
//		Select(configversion.FieldKey).
//		Scan(ctx, &v)
func (_q *ConfigVersionQuery) Select(fields ...string) *ConfigVersionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ConfigVersionSelect{ConfigVersionQuery: _q}
	sbuild.label = configversion.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ConfigVersionSelect configured with the given aggregations.
func (_q *ConfigVersionQuery) Aggregate(fns ...AggregateFunc) *ConfigVersionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ConfigVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !configversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ConfigVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ConfigVersion, error) {
	var (
		nodes       = []*ConfigVersion{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withEntry != nil,
		}
	)
	if _q.withEntry != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, configversion.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ConfigVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ConfigVersion{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEntry; query != nil {
		if err := _q.loadEntry(ctx, query, nodes, nil,
			func(n *ConfigVersion, e *ConfigEntry) { n.Edges.Entry = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ConfigVersionQuery) loadEntry(ctx context.Context, query *ConfigEntryQuery, nodes []*ConfigVersion, init func(*ConfigVersion), assign func(*ConfigVersion, *ConfigEntry)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ConfigVersion)
	for i := range nodes {
		if nodes[i].config_entry_versions == nil {
			continue
		}
		fk := *nodes[i].config_entry_versions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(configentry.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "config_entry_versions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ConfigVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ConfigVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(configversion.Table, configversion.Columns, sqlgraph.NewFieldSpec(configversion.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, configversion.FieldID)
		for i := range fields {
			if fields[i] != configversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ConfigVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(configversion.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = configversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ConfigVersionGroupBy is the group-by builder for ConfigVersion entities.
type ConfigVersionGroupBy struct {
	selector
	build *ConfigVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ConfigVersionGroupBy) Aggregate(fns ...AggregateFunc) *ConfigVersionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ConfigVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConfigVersionQuery, *ConfigVersionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ConfigVersionGroupBy) sqlScan(ctx context.Context, root *ConfigVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ConfigVersionSelect is the builder for selecting fields of ConfigVersion entities.
type ConfigVersionSelect struct {
	*ConfigVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ConfigVersionSelect) Aggregate(fns ...AggregateFunc) *ConfigVersionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ConfigVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConfigVersionQuery, *ConfigVersionSelect](ctx, _s.ConfigVersionQuery, _s, _s.inters, v)
}

func (_s *ConfigVersionSelect) sqlScan(ctx context.Context, root *ConfigVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
