// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jseer/ent/configentry"
	"jseer/ent/configversion"
	"jseer/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConfigEntryUpdate is the builder for updating ConfigEntry entities.
type ConfigEntryUpdate struct {
	config
	hooks    []Hook
	mutation *ConfigEntryMutation
}

// Where appends a list predicates to the ConfigEntryUpdate builder.
func (_u *ConfigEntryUpdate) Where(ps ...predicate.ConfigEntry) *ConfigEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *ConfigEntryUpdate) SetKey(v string) *ConfigEntryUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ConfigEntryUpdate) SetNillableKey(v *string) *ConfigEntryUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ConfigEntryUpdate) SetValue(v []byte) *ConfigEntryUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *ConfigEntryUpdate) SetVersion(v int64) *ConfigEntryUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ConfigEntryUpdate) SetNillableVersion(v *int64) *ConfigEntryUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ConfigEntryUpdate) AddVersion(v int64) *ConfigEntryUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *ConfigEntryUpdate) SetChecksum(v string) *ConfigEntryUpdate {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *ConfigEntryUpdate) SetNillableChecksum(v *string) *ConfigEntryUpdate {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConfigEntryUpdate) SetUpdatedAt(v time.Time) *ConfigEntryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddVersionIDs adds the "versions" edge to the ConfigVersion entity by IDs.
func (_u *ConfigEntryUpdate) AddVersionIDs(ids ...int) *ConfigEntryUpdate {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the ConfigVersion entity.
func (_u *ConfigEntryUpdate) AddVersions(v ...*ConfigVersion) *ConfigEntryUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// Mutation returns the ConfigEntryMutation object of the builder.
func (_u *ConfigEntryUpdate) Mutation() *ConfigEntryMutation {
	return _u.mutation
}

// ClearVersions clears all "versions" edges to the ConfigVersion entity.
func (_u *ConfigEntryUpdate) ClearVersions() *ConfigEntryUpdate {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to ConfigVersion entities by IDs.
func (_u *ConfigEntryUpdate) RemoveVersionIDs(ids ...int) *ConfigEntryUpdate {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to ConfigVersion entities.
func (_u *ConfigEntryUpdate) RemoveVersions(v ...*ConfigVersion) *ConfigEntryUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConfigEntryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConfigEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConfigEntryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := configentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ConfigEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(configentry.Table, configentry.Columns, sqlgraph.NewFieldSpec(configentry.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(configentry.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(configentry.FieldValue, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(configentry.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(configentry.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(configentry.FieldChecksum, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(configentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configentry.VersionsTable,
			Columns: []string{configentry.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configentry.VersionsTable,
			Columns: []string{configentry.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configentry.VersionsTable,
			Columns: []string{configentry.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConfigEntryUpdateOne is the builder for updating a single ConfigEntry entity.
type ConfigEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConfigEntryMutation
}

// SetKey sets the "key" field.
func (_u *ConfigEntryUpdateOne) SetKey(v string) *ConfigEntryUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ConfigEntryUpdateOne) SetNillableKey(v *string) *ConfigEntryUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ConfigEntryUpdateOne) SetValue(v []byte) *ConfigEntryUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *ConfigEntryUpdateOne) SetVersion(v int64) *ConfigEntryUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ConfigEntryUpdateOne) SetNillableVersion(v *int64) *ConfigEntryUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ConfigEntryUpdateOne) AddVersion(v int64) *ConfigEntryUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *ConfigEntryUpdateOne) SetChecksum(v string) *ConfigEntryUpdateOne {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *ConfigEntryUpdateOne) SetNillableChecksum(v *string) *ConfigEntryUpdateOne {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConfigEntryUpdateOne) SetUpdatedAt(v time.Time) *ConfigEntryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddVersionIDs adds the "versions" edge to the ConfigVersion entity by IDs.
func (_u *ConfigEntryUpdateOne) AddVersionIDs(ids ...int) *ConfigEntryUpdateOne {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the ConfigVersion entity.
func (_u *ConfigEntryUpdateOne) AddVersions(v ...*ConfigVersion) *ConfigEntryUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// Mutation returns the ConfigEntryMutation object of the builder.
func (_u *ConfigEntryUpdateOne) Mutation() *ConfigEntryMutation {
	return _u.mutation
}

// ClearVersions clears all "versions" edges to the ConfigVersion entity.
func (_u *ConfigEntryUpdateOne) ClearVersions() *ConfigEntryUpdateOne {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to ConfigVersion entities by IDs.
func (_u *ConfigEntryUpdateOne) RemoveVersionIDs(ids ...int) *ConfigEntryUpdateOne {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to ConfigVersion entities.
func (_u *ConfigEntryUpdateOne) RemoveVersions(v ...*ConfigVersion) *ConfigEntryUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// Where appends a list predicates to the ConfigEntryUpdate builder.
func (_u *ConfigEntryUpdateOne) Where(ps ...predicate.ConfigEntry) *ConfigEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConfigEntryUpdateOne) Select(field string, fields ...string) *ConfigEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConfigEntry entity.
func (_u *ConfigEntryUpdateOne) Save(ctx context.Context) (*ConfigEntry, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigEntryUpdateOne) SaveX(ctx context.Context) *ConfigEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConfigEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConfigEntryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := configentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ConfigEntryUpdateOne) sqlSave(ctx context.Context) (_node *ConfigEntry, err error) {
	_spec := sqlgraph.NewUpdateSpec(configentry.Table, configentry.Columns, sqlgraph.NewFieldSpec(configentry.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConfigEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, configentry.FieldID)
		for _, f := range fields {
			if !configentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != configentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(configentry.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(configentry.FieldValue, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(configentry.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(configentry.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(configentry.FieldChecksum, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(configentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configentry.VersionsTable,
			Columns: []string{configentry.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configentry.VersionsTable,
			Columns: []string{configentry.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configentry.VersionsTable,
			Columns: []string{configentry.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ConfigEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
