// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jseer/ent/configentry"
	"jseer/ent/configversion"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConfigEntryCreate is the builder for creating a ConfigEntry entity.
type ConfigEntryCreate struct {
	config
	mutation *ConfigEntryMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *ConfigEntryCreate) SetKey(v string) *ConfigEntryCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *ConfigEntryCreate) SetValue(v []byte) *ConfigEntryCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ConfigEntryCreate) SetVersion(v int64) *ConfigEntryCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ConfigEntryCreate) SetNillableVersion(v *int64) *ConfigEntryCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *ConfigEntryCreate) SetChecksum(v string) *ConfigEntryCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_c *ConfigEntryCreate) SetNillableChecksum(v *string) *ConfigEntryCreate {
	if v != nil {
		_c.SetChecksum(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConfigEntryCreate) SetUpdatedAt(v time.Time) *ConfigEntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConfigEntryCreate) SetNillableUpdatedAt(v *time.Time) *ConfigEntryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddVersionIDs adds the "versions" edge to the ConfigVersion entity by IDs.
func (_c *ConfigEntryCreate) AddVersionIDs(ids ...int) *ConfigEntryCreate {
	_c.mutation.AddVersionIDs(ids...)
	return _c
}

// AddVersions adds the "versions" edges to the ConfigVersion entity.
func (_c *ConfigEntryCreate) AddVersions(v ...*ConfigVersion) *ConfigEntryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVersionIDs(ids...)
}

// Mutation returns the ConfigEntryMutation object of the builder.
func (_c *ConfigEntryCreate) Mutation() *ConfigEntryMutation {
	return _c.mutation
}

// Save creates the ConfigEntry in the database.
func (_c *ConfigEntryCreate) Save(ctx context.Context) (*ConfigEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConfigEntryCreate) SaveX(ctx context.Context) *ConfigEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfigEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfigEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConfigEntryCreate) defaults() {
	if _, ok := _c.mutation.Version(); !ok {
		v := configentry.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		v := configentry.DefaultChecksum
		_c.mutation.SetChecksum(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := configentry.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConfigEntryCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "ConfigEntry.key"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "ConfigEntry.value"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ConfigEntry.version"`)}
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		return &ValidationError{Name: "checksum", err: errors.New(`ent: missing required field "ConfigEntry.checksum"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ConfigEntry.updated_at"`)}
	}
	return nil
}

func (_c *ConfigEntryCreate) sqlSave(ctx context.Context) (*ConfigEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConfigEntryCreate) createSpec() (*ConfigEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &ConfigEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(configentry.Table, sqlgraph.NewFieldSpec(configentry.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(configentry.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(configentry.FieldValue, field.TypeBytes, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(configentry.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(configentry.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(configentry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configentry.VersionsTable,
			Columns: []string{configentry.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConfigEntryCreateBulk is the builder for creating many ConfigEntry entities in bulk.
type ConfigEntryCreateBulk struct {
	config
	err      error
	builders []*ConfigEntryCreate
}

// Save creates the ConfigEntry entities in the database.
func (_c *ConfigEntryCreateBulk) Save(ctx context.Context) ([]*ConfigEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConfigEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConfigEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConfigEntryCreateBulk) SaveX(ctx context.Context) []*ConfigEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfigEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfigEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
