// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jseer/ent/account"
	"jseer/ent/item"
	"jseer/ent/pet"
	"jseer/ent/player"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlayerCreate is the builder for creating a Player entity.
type PlayerCreate struct {
	config
	mutation *PlayerMutation
	hooks    []Hook
}

// SetAccountID sets the "account_id" field.
func (_c *PlayerCreate) SetAccountID(v int) *PlayerCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNick sets the "nick" field.
func (_c *PlayerCreate) SetNick(v string) *PlayerCreate {
	_c.mutation.SetNick(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *PlayerCreate) SetLevel(v int) *PlayerCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableLevel(v *int) *PlayerCreate {
	if v != nil {
		_c.SetLevel(*v)
	}
	return _c
}

// SetCoins sets the "coins" field.
func (_c *PlayerCreate) SetCoins(v int64) *PlayerCreate {
	_c.mutation.SetCoins(v)
	return _c
}

// SetNillableCoins sets the "coins" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableCoins(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetCoins(*v)
	}
	return _c
}

// SetGold sets the "gold" field.
func (_c *PlayerCreate) SetGold(v int64) *PlayerCreate {
	_c.mutation.SetGold(v)
	return _c
}

// SetNillableGold sets the "gold" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableGold(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetGold(*v)
	}
	return _c
}

// SetMapID sets the "map_id" field.
func (_c *PlayerCreate) SetMapID(v int) *PlayerCreate {
	_c.mutation.SetMapID(v)
	return _c
}

// SetNillableMapID sets the "map_id" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableMapID(v *int) *PlayerCreate {
	if v != nil {
		_c.SetMapID(*v)
	}
	return _c
}

// SetMapType sets the "map_type" field.
func (_c *PlayerCreate) SetMapType(v int) *PlayerCreate {
	_c.mutation.SetMapType(v)
	return _c
}

// SetNillableMapType sets the "map_type" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableMapType(v *int) *PlayerCreate {
	if v != nil {
		_c.SetMapType(*v)
	}
	return _c
}

// SetPosX sets the "pos_x" field.
func (_c *PlayerCreate) SetPosX(v int) *PlayerCreate {
	_c.mutation.SetPosX(v)
	return _c
}

// SetNillablePosX sets the "pos_x" field if the given value is not nil.
func (_c *PlayerCreate) SetNillablePosX(v *int) *PlayerCreate {
	if v != nil {
		_c.SetPosX(*v)
	}
	return _c
}

// SetPosY sets the "pos_y" field.
func (_c *PlayerCreate) SetPosY(v int) *PlayerCreate {
	_c.mutation.SetPosY(v)
	return _c
}

// SetNillablePosY sets the "pos_y" field if the given value is not nil.
func (_c *PlayerCreate) SetNillablePosY(v *int) *PlayerCreate {
	if v != nil {
		_c.SetPosY(*v)
	}
	return _c
}

// SetLastMapID sets the "last_map_id" field.
func (_c *PlayerCreate) SetLastMapID(v int) *PlayerCreate {
	_c.mutation.SetLastMapID(v)
	return _c
}

// SetNillableLastMapID sets the "last_map_id" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableLastMapID(v *int) *PlayerCreate {
	if v != nil {
		_c.SetLastMapID(*v)
	}
	return _c
}

// SetColor sets the "color" field.
func (_c *PlayerCreate) SetColor(v int64) *PlayerCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableColor(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetColor(*v)
	}
	return _c
}

// SetTexture sets the "texture" field.
func (_c *PlayerCreate) SetTexture(v int64) *PlayerCreate {
	_c.mutation.SetTexture(v)
	return _c
}

// SetNillableTexture sets the "texture" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableTexture(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetTexture(*v)
	}
	return _c
}

// SetEnergy sets the "energy" field.
func (_c *PlayerCreate) SetEnergy(v int64) *PlayerCreate {
	_c.mutation.SetEnergy(v)
	return _c
}

// SetNillableEnergy sets the "energy" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableEnergy(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetEnergy(*v)
	}
	return _c
}

// SetFightBadge sets the "fight_badge" field.
func (_c *PlayerCreate) SetFightBadge(v int64) *PlayerCreate {
	_c.mutation.SetFightBadge(v)
	return _c
}

// SetNillableFightBadge sets the "fight_badge" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableFightBadge(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetFightBadge(*v)
	}
	return _c
}

// SetTimeToday sets the "time_today" field.
func (_c *PlayerCreate) SetTimeToday(v int64) *PlayerCreate {
	_c.mutation.SetTimeToday(v)
	return _c
}

// SetNillableTimeToday sets the "time_today" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableTimeToday(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetTimeToday(*v)
	}
	return _c
}

// SetTimeLimit sets the "time_limit" field.
func (_c *PlayerCreate) SetTimeLimit(v int64) *PlayerCreate {
	_c.mutation.SetTimeLimit(v)
	return _c
}

// SetNillableTimeLimit sets the "time_limit" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableTimeLimit(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetTimeLimit(*v)
	}
	return _c
}

// SetTeacherID sets the "teacher_id" field.
func (_c *PlayerCreate) SetTeacherID(v int64) *PlayerCreate {
	_c.mutation.SetTeacherID(v)
	return _c
}

// SetNillableTeacherID sets the "teacher_id" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableTeacherID(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetTeacherID(*v)
	}
	return _c
}

// SetStudentID sets the "student_id" field.
func (_c *PlayerCreate) SetStudentID(v int64) *PlayerCreate {
	_c.mutation.SetStudentID(v)
	return _c
}

// SetNillableStudentID sets the "student_id" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableStudentID(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetStudentID(*v)
	}
	return _c
}

// SetCurTitle sets the "cur_title" field.
func (_c *PlayerCreate) SetCurTitle(v int64) *PlayerCreate {
	_c.mutation.SetCurTitle(v)
	return _c
}

// SetNillableCurTitle sets the "cur_title" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableCurTitle(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetCurTitle(*v)
	}
	return _c
}

// SetTaskStatus sets the "task_status" field.
func (_c *PlayerCreate) SetTaskStatus(v string) *PlayerCreate {
	_c.mutation.SetTaskStatus(v)
	return _c
}

// SetNillableTaskStatus sets the "task_status" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableTaskStatus(v *string) *PlayerCreate {
	if v != nil {
		_c.SetTaskStatus(*v)
	}
	return _c
}

// SetTaskBufs sets the "task_bufs" field.
func (_c *PlayerCreate) SetTaskBufs(v string) *PlayerCreate {
	_c.mutation.SetTaskBufs(v)
	return _c
}

// SetNillableTaskBufs sets the "task_bufs" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableTaskBufs(v *string) *PlayerCreate {
	if v != nil {
		_c.SetTaskBufs(*v)
	}
	return _c
}

// SetCurrentPetID sets the "current_pet_id" field.
func (_c *PlayerCreate) SetCurrentPetID(v int64) *PlayerCreate {
	_c.mutation.SetCurrentPetID(v)
	return _c
}

// SetNillableCurrentPetID sets the "current_pet_id" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableCurrentPetID(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetCurrentPetID(*v)
	}
	return _c
}

// SetCurrentPetCatchTime sets the "current_pet_catch_time" field.
func (_c *PlayerCreate) SetCurrentPetCatchTime(v int64) *PlayerCreate {
	_c.mutation.SetCurrentPetCatchTime(v)
	return _c
}

// SetNillableCurrentPetCatchTime sets the "current_pet_catch_time" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableCurrentPetCatchTime(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetCurrentPetCatchTime(*v)
	}
	return _c
}

// SetCurrentPetDv sets the "current_pet_dv" field.
func (_c *PlayerCreate) SetCurrentPetDv(v int64) *PlayerCreate {
	_c.mutation.SetCurrentPetDv(v)
	return _c
}

// SetNillableCurrentPetDv sets the "current_pet_dv" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableCurrentPetDv(v *int64) *PlayerCreate {
	if v != nil {
		_c.SetCurrentPetDv(*v)
	}
	return _c
}

// SetLastLoginAt sets the "last_login_at" field.
func (_c *PlayerCreate) SetLastLoginAt(v time.Time) *PlayerCreate {
	_c.mutation.SetLastLoginAt(v)
	return _c
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableLastLoginAt(v *time.Time) *PlayerCreate {
	if v != nil {
		_c.SetLastLoginAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlayerCreate) SetCreatedAt(v time.Time) *PlayerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableCreatedAt(v *time.Time) *PlayerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlayerCreate) SetUpdatedAt(v time.Time) *PlayerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableUpdatedAt(v *time.Time) *PlayerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *PlayerCreate) SetAccount(v *Account) *PlayerCreate {
	return _c.SetAccountID(v.ID)
}

// AddPetIDs adds the "pets" edge to the Pet entity by IDs.
func (_c *PlayerCreate) AddPetIDs(ids ...int) *PlayerCreate {
	_c.mutation.AddPetIDs(ids...)
	return _c
}

// AddPets adds the "pets" edges to the Pet entity.
func (_c *PlayerCreate) AddPets(v ...*Pet) *PlayerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPetIDs(ids...)
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (_c *PlayerCreate) AddItemIDs(ids ...int) *PlayerCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the Item entity.
func (_c *PlayerCreate) AddItems(v ...*Item) *PlayerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the PlayerMutation object of the builder.
func (_c *PlayerCreate) Mutation() *PlayerMutation {
	return _c.mutation
}

// Save creates the Player in the database.
func (_c *PlayerCreate) Save(ctx context.Context) (*Player, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlayerCreate) SaveX(ctx context.Context) *Player {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlayerCreate) defaults() {
	if _, ok := _c.mutation.Level(); !ok {
		v := player.DefaultLevel
		_c.mutation.SetLevel(v)
	}
	if _, ok := _c.mutation.Coins(); !ok {
		v := player.DefaultCoins
		_c.mutation.SetCoins(v)
	}
	if _, ok := _c.mutation.Gold(); !ok {
		v := player.DefaultGold
		_c.mutation.SetGold(v)
	}
	if _, ok := _c.mutation.MapID(); !ok {
		v := player.DefaultMapID
		_c.mutation.SetMapID(v)
	}
	if _, ok := _c.mutation.MapType(); !ok {
		v := player.DefaultMapType
		_c.mutation.SetMapType(v)
	}
	if _, ok := _c.mutation.PosX(); !ok {
		v := player.DefaultPosX
		_c.mutation.SetPosX(v)
	}
	if _, ok := _c.mutation.PosY(); !ok {
		v := player.DefaultPosY
		_c.mutation.SetPosY(v)
	}
	if _, ok := _c.mutation.LastMapID(); !ok {
		v := player.DefaultLastMapID
		_c.mutation.SetLastMapID(v)
	}
	if _, ok := _c.mutation.Color(); !ok {
		v := player.DefaultColor
		_c.mutation.SetColor(v)
	}
	if _, ok := _c.mutation.Texture(); !ok {
		v := player.DefaultTexture
		_c.mutation.SetTexture(v)
	}
	if _, ok := _c.mutation.Energy(); !ok {
		v := player.DefaultEnergy
		_c.mutation.SetEnergy(v)
	}
	if _, ok := _c.mutation.FightBadge(); !ok {
		v := player.DefaultFightBadge
		_c.mutation.SetFightBadge(v)
	}
	if _, ok := _c.mutation.TimeToday(); !ok {
		v := player.DefaultTimeToday
		_c.mutation.SetTimeToday(v)
	}
	if _, ok := _c.mutation.TimeLimit(); !ok {
		v := player.DefaultTimeLimit
		_c.mutation.SetTimeLimit(v)
	}
	if _, ok := _c.mutation.TeacherID(); !ok {
		v := player.DefaultTeacherID
		_c.mutation.SetTeacherID(v)
	}
	if _, ok := _c.mutation.StudentID(); !ok {
		v := player.DefaultStudentID
		_c.mutation.SetStudentID(v)
	}
	if _, ok := _c.mutation.CurTitle(); !ok {
		v := player.DefaultCurTitle
		_c.mutation.SetCurTitle(v)
	}
	if _, ok := _c.mutation.TaskStatus(); !ok {
		v := player.DefaultTaskStatus
		_c.mutation.SetTaskStatus(v)
	}
	if _, ok := _c.mutation.TaskBufs(); !ok {
		v := player.DefaultTaskBufs
		_c.mutation.SetTaskBufs(v)
	}
	if _, ok := _c.mutation.CurrentPetID(); !ok {
		v := player.DefaultCurrentPetID
		_c.mutation.SetCurrentPetID(v)
	}
	if _, ok := _c.mutation.CurrentPetCatchTime(); !ok {
		v := player.DefaultCurrentPetCatchTime
		_c.mutation.SetCurrentPetCatchTime(v)
	}
	if _, ok := _c.mutation.CurrentPetDv(); !ok {
		v := player.DefaultCurrentPetDv
		_c.mutation.SetCurrentPetDv(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := player.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := player.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlayerCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "Player.account_id"`)}
	}
	if _, ok := _c.mutation.Nick(); !ok {
		return &ValidationError{Name: "nick", err: errors.New(`ent: missing required field "Player.nick"`)}
	}
	if v, ok := _c.mutation.Nick(); ok {
		if err := player.NickValidator(v); err != nil {
			return &ValidationError{Name: "nick", err: fmt.Errorf(`ent: validator failed for field "Player.nick": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Player.level"`)}
	}
	if _, ok := _c.mutation.Coins(); !ok {
		return &ValidationError{Name: "coins", err: errors.New(`ent: missing required field "Player.coins"`)}
	}
	if _, ok := _c.mutation.Gold(); !ok {
		return &ValidationError{Name: "gold", err: errors.New(`ent: missing required field "Player.gold"`)}
	}
	if _, ok := _c.mutation.MapID(); !ok {
		return &ValidationError{Name: "map_id", err: errors.New(`ent: missing required field "Player.map_id"`)}
	}
	if _, ok := _c.mutation.MapType(); !ok {
		return &ValidationError{Name: "map_type", err: errors.New(`ent: missing required field "Player.map_type"`)}
	}
	if _, ok := _c.mutation.PosX(); !ok {
		return &ValidationError{Name: "pos_x", err: errors.New(`ent: missing required field "Player.pos_x"`)}
	}
	if _, ok := _c.mutation.PosY(); !ok {
		return &ValidationError{Name: "pos_y", err: errors.New(`ent: missing required field "Player.pos_y"`)}
	}
	if _, ok := _c.mutation.LastMapID(); !ok {
		return &ValidationError{Name: "last_map_id", err: errors.New(`ent: missing required field "Player.last_map_id"`)}
	}
	if _, ok := _c.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "Player.color"`)}
	}
	if _, ok := _c.mutation.Texture(); !ok {
		return &ValidationError{Name: "texture", err: errors.New(`ent: missing required field "Player.texture"`)}
	}
	if _, ok := _c.mutation.Energy(); !ok {
		return &ValidationError{Name: "energy", err: errors.New(`ent: missing required field "Player.energy"`)}
	}
	if _, ok := _c.mutation.FightBadge(); !ok {
		return &ValidationError{Name: "fight_badge", err: errors.New(`ent: missing required field "Player.fight_badge"`)}
	}
	if _, ok := _c.mutation.TimeToday(); !ok {
		return &ValidationError{Name: "time_today", err: errors.New(`ent: missing required field "Player.time_today"`)}
	}
	if _, ok := _c.mutation.TimeLimit(); !ok {
		return &ValidationError{Name: "time_limit", err: errors.New(`ent: missing required field "Player.time_limit"`)}
	}
	if _, ok := _c.mutation.TeacherID(); !ok {
		return &ValidationError{Name: "teacher_id", err: errors.New(`ent: missing required field "Player.teacher_id"`)}
	}
	if _, ok := _c.mutation.StudentID(); !ok {
		return &ValidationError{Name: "student_id", err: errors.New(`ent: missing required field "Player.student_id"`)}
	}
	if _, ok := _c.mutation.CurTitle(); !ok {
		return &ValidationError{Name: "cur_title", err: errors.New(`ent: missing required field "Player.cur_title"`)}
	}
	if _, ok := _c.mutation.TaskStatus(); !ok {
		return &ValidationError{Name: "task_status", err: errors.New(`ent: missing required field "Player.task_status"`)}
	}
	if _, ok := _c.mutation.TaskBufs(); !ok {
		return &ValidationError{Name: "task_bufs", err: errors.New(`ent: missing required field "Player.task_bufs"`)}
	}
	if _, ok := _c.mutation.CurrentPetID(); !ok {
		return &ValidationError{Name: "current_pet_id", err: errors.New(`ent: missing required field "Player.current_pet_id"`)}
	}
	if _, ok := _c.mutation.CurrentPetCatchTime(); !ok {
		return &ValidationError{Name: "current_pet_catch_time", err: errors.New(`ent: missing required field "Player.current_pet_catch_time"`)}
	}
	if _, ok := _c.mutation.CurrentPetDv(); !ok {
		return &ValidationError{Name: "current_pet_dv", err: errors.New(`ent: missing required field "Player.current_pet_dv"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Player.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Player.updated_at"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "Player.account"`)}
	}
	return nil
}

func (_c *PlayerCreate) sqlSave(ctx context.Context) (*Player, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlayerCreate) createSpec() (*Player, *sqlgraph.CreateSpec) {
	var (
		_node = &Player{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(player.Table, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Nick(); ok {
		_spec.SetField(player.FieldNick, field.TypeString, value)
		_node.Nick = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(player.FieldLevel, field.TypeInt, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Coins(); ok {
		_spec.SetField(player.FieldCoins, field.TypeInt64, value)
		_node.Coins = value
	}
	if value, ok := _c.mutation.Gold(); ok {
		_spec.SetField(player.FieldGold, field.TypeInt64, value)
		_node.Gold = value
	}
	if value, ok := _c.mutation.MapID(); ok {
		_spec.SetField(player.FieldMapID, field.TypeInt, value)
		_node.MapID = value
	}
	if value, ok := _c.mutation.MapType(); ok {
		_spec.SetField(player.FieldMapType, field.TypeInt, value)
		_node.MapType = value
	}
	if value, ok := _c.mutation.PosX(); ok {
		_spec.SetField(player.FieldPosX, field.TypeInt, value)
		_node.PosX = value
	}
	if value, ok := _c.mutation.PosY(); ok {
		_spec.SetField(player.FieldPosY, field.TypeInt, value)
		_node.PosY = value
	}
	if value, ok := _c.mutation.LastMapID(); ok {
		_spec.SetField(player.FieldLastMapID, field.TypeInt, value)
		_node.LastMapID = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(player.FieldColor, field.TypeInt64, value)
		_node.Color = value
	}
	if value, ok := _c.mutation.Texture(); ok {
		_spec.SetField(player.FieldTexture, field.TypeInt64, value)
		_node.Texture = value
	}
	if value, ok := _c.mutation.Energy(); ok {
		_spec.SetField(player.FieldEnergy, field.TypeInt64, value)
		_node.Energy = value
	}
	if value, ok := _c.mutation.FightBadge(); ok {
		_spec.SetField(player.FieldFightBadge, field.TypeInt64, value)
		_node.FightBadge = value
	}
	if value, ok := _c.mutation.TimeToday(); ok {
		_spec.SetField(player.FieldTimeToday, field.TypeInt64, value)
		_node.TimeToday = value
	}
	if value, ok := _c.mutation.TimeLimit(); ok {
		_spec.SetField(player.FieldTimeLimit, field.TypeInt64, value)
		_node.TimeLimit = value
	}
	if value, ok := _c.mutation.TeacherID(); ok {
		_spec.SetField(player.FieldTeacherID, field.TypeInt64, value)
		_node.TeacherID = value
	}
	if value, ok := _c.mutation.StudentID(); ok {
		_spec.SetField(player.FieldStudentID, field.TypeInt64, value)
		_node.StudentID = value
	}
	if value, ok := _c.mutation.CurTitle(); ok {
		_spec.SetField(player.FieldCurTitle, field.TypeInt64, value)
		_node.CurTitle = value
	}
	if value, ok := _c.mutation.TaskStatus(); ok {
		_spec.SetField(player.FieldTaskStatus, field.TypeString, value)
		_node.TaskStatus = value
	}
	if value, ok := _c.mutation.TaskBufs(); ok {
		_spec.SetField(player.FieldTaskBufs, field.TypeString, value)
		_node.TaskBufs = value
	}
	if value, ok := _c.mutation.CurrentPetID(); ok {
		_spec.SetField(player.FieldCurrentPetID, field.TypeInt64, value)
		_node.CurrentPetID = value
	}
	if value, ok := _c.mutation.CurrentPetCatchTime(); ok {
		_spec.SetField(player.FieldCurrentPetCatchTime, field.TypeInt64, value)
		_node.CurrentPetCatchTime = value
	}
	if value, ok := _c.mutation.CurrentPetDv(); ok {
		_spec.SetField(player.FieldCurrentPetDv, field.TypeInt64, value)
		_node.CurrentPetDv = value
	}
	if value, ok := _c.mutation.LastLoginAt(); ok {
		_spec.SetField(player.FieldLastLoginAt, field.TypeTime, value)
		_node.LastLoginAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(player.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(player.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.AccountTable,
			Columns: []string{player.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.PetsTable,
			Columns: []string{player.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.ItemsTable,
			Columns: []string{player.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlayerCreateBulk is the builder for creating many Player entities in bulk.
type PlayerCreateBulk struct {
	config
	err      error
	builders []*PlayerCreate
}

// Save creates the Player entities in the database.
func (_c *PlayerCreateBulk) Save(ctx context.Context) ([]*Player, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Player, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlayerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlayerCreateBulk) SaveX(ctx context.Context) []*Player {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
