// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jseer/ent/account"
	"jseer/ent/item"
	"jseer/ent/pet"
	"jseer/ent/player"
	"jseer/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlayerUpdate is the builder for updating Player entities.
type PlayerUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerMutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdate) Where(ps ...predicate.Player) *PlayerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *PlayerUpdate) SetAccountID(v int) *PlayerUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableAccountID(v *int) *PlayerUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetNick sets the "nick" field.
func (_u *PlayerUpdate) SetNick(v string) *PlayerUpdate {
	_u.mutation.SetNick(v)
	return _u
}

// SetNillableNick sets the "nick" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableNick(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetNick(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *PlayerUpdate) SetLevel(v int) *PlayerUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableLevel(v *int) *PlayerUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *PlayerUpdate) AddLevel(v int) *PlayerUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetCoins sets the "coins" field.
func (_u *PlayerUpdate) SetCoins(v int64) *PlayerUpdate {
	_u.mutation.ResetCoins()
	_u.mutation.SetCoins(v)
	return _u
}

// SetNillableCoins sets the "coins" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableCoins(v *int64) *PlayerUpdate {
	if v != nil {
		_u.SetCoins(*v)
	}
	return _u
}

// AddCoins adds value to the "coins" field.
func (_u *PlayerUpdate) AddCoins(v int64) *PlayerUpdate {
	_u.mutation.AddCoins(v)
	return _u
}

// SetGold sets the "gold" field.
func (_u *PlayerUpdate) SetGold(v int64) *PlayerUpdate {
	_u.mutation.ResetGold()
	_u.mutation.SetGold(v)
	return _u
}

// SetNillableGold sets the "gold" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableGold(v *int64) *PlayerUpdate {
	if v != nil {
		_u.SetGold(*v)
	}
	return _u
}

// AddGold adds value to the "gold" field.
func (_u *PlayerUpdate) AddGold(v int64) *PlayerUpdate {
	_u.mutation.AddGold(v)
	return _u
}

// SetMapID sets the "map_id" field.
func (_u *PlayerUpdate) SetMapID(v int) *PlayerUpdate {
	_u.mutation.ResetMapID()
	_u.mutation.SetMapID(v)
	return _u
}

// SetNillableMapID sets the "map_id" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableMapID(v *int) *PlayerUpdate {
	if v != nil {
		_u.SetMapID(*v)
	}
	return _u
}

// AddMapID adds value to the "map_id" field.
func (_u *PlayerUpdate) AddMapID(v int) *PlayerUpdate {
	_u.mutation.AddMapID(v)
	return _u
}

// SetPosX sets the "pos_x" field.
func (_u *PlayerUpdate) SetPosX(v int) *PlayerUpdate {
	_u.mutation.ResetPosX()
	_u.mutation.SetPosX(v)
	return _u
}

// SetNillablePosX sets the "pos_x" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillablePosX(v *int) *PlayerUpdate {
	if v != nil {
		_u.SetPosX(*v)
	}
	return _u
}

// AddPosX adds value to the "pos_x" field.
func (_u *PlayerUpdate) AddPosX(v int) *PlayerUpdate {
	_u.mutation.AddPosX(v)
	return _u
}

// SetPosY sets the "pos_y" field.
func (_u *PlayerUpdate) SetPosY(v int) *PlayerUpdate {
	_u.mutation.ResetPosY()
	_u.mutation.SetPosY(v)
	return _u
}

// SetNillablePosY sets the "pos_y" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillablePosY(v *int) *PlayerUpdate {
	if v != nil {
		_u.SetPosY(*v)
	}
	return _u
}

// AddPosY adds value to the "pos_y" field.
func (_u *PlayerUpdate) AddPosY(v int) *PlayerUpdate {
	_u.mutation.AddPosY(v)
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *PlayerUpdate) SetLastLoginAt(v time.Time) *PlayerUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableLastLoginAt(v *time.Time) *PlayerUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *PlayerUpdate) ClearLastLoginAt() *PlayerUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PlayerUpdate) SetCreatedAt(v time.Time) *PlayerUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableCreatedAt(v *time.Time) *PlayerUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlayerUpdate) SetUpdatedAt(v time.Time) *PlayerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *PlayerUpdate) SetAccount(v *Account) *PlayerUpdate {
	return _u.SetAccountID(v.ID)
}

// AddPetIDs adds the "pets" edge to the Pet entity by IDs.
func (_u *PlayerUpdate) AddPetIDs(ids ...int) *PlayerUpdate {
	_u.mutation.AddPetIDs(ids...)
	return _u
}

// AddPets adds the "pets" edges to the Pet entity.
func (_u *PlayerUpdate) AddPets(v ...*Pet) *PlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPetIDs(ids...)
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (_u *PlayerUpdate) AddItemIDs(ids ...int) *PlayerUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the Item entity.
func (_u *PlayerUpdate) AddItems(v ...*Item) *PlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdate) Mutation() *PlayerMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *PlayerUpdate) ClearAccount() *PlayerUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearPets clears all "pets" edges to the Pet entity.
func (_u *PlayerUpdate) ClearPets() *PlayerUpdate {
	_u.mutation.ClearPets()
	return _u
}

// RemovePetIDs removes the "pets" edge to Pet entities by IDs.
func (_u *PlayerUpdate) RemovePetIDs(ids ...int) *PlayerUpdate {
	_u.mutation.RemovePetIDs(ids...)
	return _u
}

// RemovePets removes "pets" edges to Pet entities.
func (_u *PlayerUpdate) RemovePets(v ...*Pet) *PlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePetIDs(ids...)
}

// ClearItems clears all "items" edges to the Item entity.
func (_u *PlayerUpdate) ClearItems() *PlayerUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (_u *PlayerUpdate) RemoveItemIDs(ids ...int) *PlayerUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to Item entities.
func (_u *PlayerUpdate) RemoveItems(v ...*Item) *PlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlayerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlayerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlayerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := player.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdate) check() error {
	if v, ok := _u.mutation.Nick(); ok {
		if err := player.NickValidator(v); err != nil {
			return &ValidationError{Name: "nick", err: fmt.Errorf(`ent: validator failed for field "Player.nick": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Player.account"`)
	}
	return nil
}

func (_u *PlayerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nick(); ok {
		_spec.SetField(player.FieldNick, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(player.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(player.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Coins(); ok {
		_spec.SetField(player.FieldCoins, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCoins(); ok {
		_spec.AddField(player.FieldCoins, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Gold(); ok {
		_spec.SetField(player.FieldGold, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGold(); ok {
		_spec.AddField(player.FieldGold, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MapID(); ok {
		_spec.SetField(player.FieldMapID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMapID(); ok {
		_spec.AddField(player.FieldMapID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PosX(); ok {
		_spec.SetField(player.FieldPosX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosX(); ok {
		_spec.AddField(player.FieldPosX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PosY(); ok {
		_spec.SetField(player.FieldPosY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosY(); ok {
		_spec.AddField(player.FieldPosY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(player.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(player.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(player.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(player.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.AccountTable,
			Columns: []string{player.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.AccountTable,
			Columns: []string{player.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.PetsTable,
			Columns: []string{player.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPetsIDs(); len(nodes) > 0 && !_u.mutation.PetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.PetsTable,
			Columns: []string{player.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.PetsTable,
			Columns: []string{player.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.ItemsTable,
			Columns: []string{player.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.ItemsTable,
			Columns: []string{player.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.ItemsTable,
			Columns: []string{player.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlayerUpdateOne is the builder for updating a single Player entity.
type PlayerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerMutation
}

// SetAccountID sets the "account_id" field.
func (_u *PlayerUpdateOne) SetAccountID(v int) *PlayerUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableAccountID(v *int) *PlayerUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetNick sets the "nick" field.
func (_u *PlayerUpdateOne) SetNick(v string) *PlayerUpdateOne {
	_u.mutation.SetNick(v)
	return _u
}

// SetNillableNick sets the "nick" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableNick(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetNick(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *PlayerUpdateOne) SetLevel(v int) *PlayerUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableLevel(v *int) *PlayerUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *PlayerUpdateOne) AddLevel(v int) *PlayerUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetCoins sets the "coins" field.
func (_u *PlayerUpdateOne) SetCoins(v int64) *PlayerUpdateOne {
	_u.mutation.ResetCoins()
	_u.mutation.SetCoins(v)
	return _u
}

// SetNillableCoins sets the "coins" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableCoins(v *int64) *PlayerUpdateOne {
	if v != nil {
		_u.SetCoins(*v)
	}
	return _u
}

// AddCoins adds value to the "coins" field.
func (_u *PlayerUpdateOne) AddCoins(v int64) *PlayerUpdateOne {
	_u.mutation.AddCoins(v)
	return _u
}

// SetGold sets the "gold" field.
func (_u *PlayerUpdateOne) SetGold(v int64) *PlayerUpdateOne {
	_u.mutation.ResetGold()
	_u.mutation.SetGold(v)
	return _u
}

// SetNillableGold sets the "gold" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableGold(v *int64) *PlayerUpdateOne {
	if v != nil {
		_u.SetGold(*v)
	}
	return _u
}

// AddGold adds value to the "gold" field.
func (_u *PlayerUpdateOne) AddGold(v int64) *PlayerUpdateOne {
	_u.mutation.AddGold(v)
	return _u
}

// SetMapID sets the "map_id" field.
func (_u *PlayerUpdateOne) SetMapID(v int) *PlayerUpdateOne {
	_u.mutation.ResetMapID()
	_u.mutation.SetMapID(v)
	return _u
}

// SetNillableMapID sets the "map_id" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableMapID(v *int) *PlayerUpdateOne {
	if v != nil {
		_u.SetMapID(*v)
	}
	return _u
}

// AddMapID adds value to the "map_id" field.
func (_u *PlayerUpdateOne) AddMapID(v int) *PlayerUpdateOne {
	_u.mutation.AddMapID(v)
	return _u
}

// SetPosX sets the "pos_x" field.
func (_u *PlayerUpdateOne) SetPosX(v int) *PlayerUpdateOne {
	_u.mutation.ResetPosX()
	_u.mutation.SetPosX(v)
	return _u
}

// SetNillablePosX sets the "pos_x" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillablePosX(v *int) *PlayerUpdateOne {
	if v != nil {
		_u.SetPosX(*v)
	}
	return _u
}

// AddPosX adds value to the "pos_x" field.
func (_u *PlayerUpdateOne) AddPosX(v int) *PlayerUpdateOne {
	_u.mutation.AddPosX(v)
	return _u
}

// SetPosY sets the "pos_y" field.
func (_u *PlayerUpdateOne) SetPosY(v int) *PlayerUpdateOne {
	_u.mutation.ResetPosY()
	_u.mutation.SetPosY(v)
	return _u
}

// SetNillablePosY sets the "pos_y" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillablePosY(v *int) *PlayerUpdateOne {
	if v != nil {
		_u.SetPosY(*v)
	}
	return _u
}

// AddPosY adds value to the "pos_y" field.
func (_u *PlayerUpdateOne) AddPosY(v int) *PlayerUpdateOne {
	_u.mutation.AddPosY(v)
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *PlayerUpdateOne) SetLastLoginAt(v time.Time) *PlayerUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableLastLoginAt(v *time.Time) *PlayerUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *PlayerUpdateOne) ClearLastLoginAt() *PlayerUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PlayerUpdateOne) SetCreatedAt(v time.Time) *PlayerUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableCreatedAt(v *time.Time) *PlayerUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlayerUpdateOne) SetUpdatedAt(v time.Time) *PlayerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *PlayerUpdateOne) SetAccount(v *Account) *PlayerUpdateOne {
	return _u.SetAccountID(v.ID)
}

// AddPetIDs adds the "pets" edge to the Pet entity by IDs.
func (_u *PlayerUpdateOne) AddPetIDs(ids ...int) *PlayerUpdateOne {
	_u.mutation.AddPetIDs(ids...)
	return _u
}

// AddPets adds the "pets" edges to the Pet entity.
func (_u *PlayerUpdateOne) AddPets(v ...*Pet) *PlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPetIDs(ids...)
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (_u *PlayerUpdateOne) AddItemIDs(ids ...int) *PlayerUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the Item entity.
func (_u *PlayerUpdateOne) AddItems(v ...*Item) *PlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdateOne) Mutation() *PlayerMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *PlayerUpdateOne) ClearAccount() *PlayerUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearPets clears all "pets" edges to the Pet entity.
func (_u *PlayerUpdateOne) ClearPets() *PlayerUpdateOne {
	_u.mutation.ClearPets()
	return _u
}

// RemovePetIDs removes the "pets" edge to Pet entities by IDs.
func (_u *PlayerUpdateOne) RemovePetIDs(ids ...int) *PlayerUpdateOne {
	_u.mutation.RemovePetIDs(ids...)
	return _u
}

// RemovePets removes "pets" edges to Pet entities.
func (_u *PlayerUpdateOne) RemovePets(v ...*Pet) *PlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePetIDs(ids...)
}

// ClearItems clears all "items" edges to the Item entity.
func (_u *PlayerUpdateOne) ClearItems() *PlayerUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to Item entities by IDs.
func (_u *PlayerUpdateOne) RemoveItemIDs(ids ...int) *PlayerUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to Item entities.
func (_u *PlayerUpdateOne) RemoveItems(v ...*Item) *PlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdateOne) Where(ps ...predicate.Player) *PlayerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlayerUpdateOne) Select(field string, fields ...string) *PlayerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Player entity.
func (_u *PlayerUpdateOne) Save(ctx context.Context) (*Player, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdateOne) SaveX(ctx context.Context) *Player {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlayerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlayerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := player.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdateOne) check() error {
	if v, ok := _u.mutation.Nick(); ok {
		if err := player.NickValidator(v); err != nil {
			return &ValidationError{Name: "nick", err: fmt.Errorf(`ent: validator failed for field "Player.nick": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Player.account"`)
	}
	return nil
}

func (_u *PlayerUpdateOne) sqlSave(ctx context.Context) (_node *Player, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Player.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, player.FieldID)
		for _, f := range fields {
			if !player.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != player.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nick(); ok {
		_spec.SetField(player.FieldNick, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(player.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(player.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Coins(); ok {
		_spec.SetField(player.FieldCoins, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCoins(); ok {
		_spec.AddField(player.FieldCoins, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Gold(); ok {
		_spec.SetField(player.FieldGold, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGold(); ok {
		_spec.AddField(player.FieldGold, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MapID(); ok {
		_spec.SetField(player.FieldMapID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMapID(); ok {
		_spec.AddField(player.FieldMapID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PosX(); ok {
		_spec.SetField(player.FieldPosX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosX(); ok {
		_spec.AddField(player.FieldPosX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PosY(); ok {
		_spec.SetField(player.FieldPosY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosY(); ok {
		_spec.AddField(player.FieldPosY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(player.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(player.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(player.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(player.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.AccountTable,
			Columns: []string{player.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.AccountTable,
			Columns: []string{player.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.PetsTable,
			Columns: []string{player.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPetsIDs(); len(nodes) > 0 && !_u.mutation.PetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.PetsTable,
			Columns: []string{player.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.PetsTable,
			Columns: []string{player.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.ItemsTable,
			Columns: []string{player.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.ItemsTable,
			Columns: []string{player.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.ItemsTable,
			Columns: []string{player.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Player{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
