// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"jseer/ent/account"
	"jseer/ent/player"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Player is the model entity for the Player schema.
type Player struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int `json:"account_id,omitempty"`
	// Nick holds the value of the "nick" field.
	Nick string `json:"nick,omitempty"`
	// Level holds the value of the "level" field.
	Level int `json:"level,omitempty"`
	// Coins holds the value of the "coins" field.
	Coins int64 `json:"coins,omitempty"`
	// Gold holds the value of the "gold" field.
	Gold int64 `json:"gold,omitempty"`
	// MapID holds the value of the "map_id" field.
	MapID int `json:"map_id,omitempty"`
	// PosX holds the value of the "pos_x" field.
	PosX int `json:"pos_x,omitempty"`
	// PosY holds the value of the "pos_y" field.
	PosY int `json:"pos_y,omitempty"`
	// LastLoginAt holds the value of the "last_login_at" field.
	LastLoginAt time.Time `json:"last_login_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlayerQuery when eager-loading is set.
	Edges        PlayerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlayerEdges holds the relations/edges for other nodes in the graph.
type PlayerEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Pets holds the value of the pets edge.
	Pets []*Pet `json:"pets,omitempty"`
	// Items holds the value of the items edge.
	Items []*Item `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayerEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// PetsOrErr returns the Pets value or an error if the edge
// was not loaded in eager-loading.
func (e PlayerEdges) PetsOrErr() ([]*Pet, error) {
	if e.loadedTypes[1] {
		return e.Pets, nil
	}
	return nil, &NotLoadedError{edge: "pets"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e PlayerEdges) ItemsOrErr() ([]*Item, error) {
	if e.loadedTypes[2] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Player) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case player.FieldID, player.FieldAccountID, player.FieldLevel, player.FieldCoins, player.FieldGold, player.FieldMapID, player.FieldPosX, player.FieldPosY:
			values[i] = new(sql.NullInt64)
		case player.FieldNick:
			values[i] = new(sql.NullString)
		case player.FieldLastLoginAt, player.FieldCreatedAt, player.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Player fields.
func (_m *Player) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case player.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case player.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = int(value.Int64)
			}
		case player.FieldNick:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nick", values[i])
			} else if value.Valid {
				_m.Nick = value.String
			}
		case player.FieldLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = int(value.Int64)
			}
		case player.FieldCoins:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field coins", values[i])
			} else if value.Valid {
				_m.Coins = value.Int64
			}
		case player.FieldGold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gold", values[i])
			} else if value.Valid {
				_m.Gold = value.Int64
			}
		case player.FieldMapID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field map_id", values[i])
			} else if value.Valid {
				_m.MapID = int(value.Int64)
			}
		case player.FieldPosX:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pos_x", values[i])
			} else if value.Valid {
				_m.PosX = int(value.Int64)
			}
		case player.FieldPosY:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pos_y", values[i])
			} else if value.Valid {
				_m.PosY = int(value.Int64)
			}
		case player.FieldLastLoginAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login_at", values[i])
			} else if value.Valid {
				_m.LastLoginAt = value.Time
			}
		case player.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case player.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Player.
// This includes values selected through modifiers, order, etc.
func (_m *Player) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the Player entity.
func (_m *Player) QueryAccount() *AccountQuery {
	return NewPlayerClient(_m.config).QueryAccount(_m)
}

// QueryPets queries the "pets" edge of the Player entity.
func (_m *Player) QueryPets() *PetQuery {
	return NewPlayerClient(_m.config).QueryPets(_m)
}

// QueryItems queries the "items" edge of the Player entity.
func (_m *Player) QueryItems() *ItemQuery {
	return NewPlayerClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this Player.
// Note that you need to call Player.Unwrap() before calling this method if this Player
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Player) Update() *PlayerUpdateOne {
	return NewPlayerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Player entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Player) Unwrap() *Player {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Player is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Player) String() string {
	var builder strings.Builder
	builder.WriteString("Player(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("nick=")
	builder.WriteString(_m.Nick)
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", _m.Level))
	builder.WriteString(", ")
	builder.WriteString("coins=")
	builder.WriteString(fmt.Sprintf("%v", _m.Coins))
	builder.WriteString(", ")
	builder.WriteString("gold=")
	builder.WriteString(fmt.Sprintf("%v", _m.Gold))
	builder.WriteString(", ")
	builder.WriteString("map_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MapID))
	builder.WriteString(", ")
	builder.WriteString("pos_x=")
	builder.WriteString(fmt.Sprintf("%v", _m.PosX))
	builder.WriteString(", ")
	builder.WriteString("pos_y=")
	builder.WriteString(fmt.Sprintf("%v", _m.PosY))
	builder.WriteString(", ")
	builder.WriteString("last_login_at=")
	builder.WriteString(_m.LastLoginAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Players is a parsable slice of Player.
type Players []*Player
