// Code generated by ent, DO NOT EDIT.

package ent

import (
	"jseer/ent/account"
	"jseer/ent/auditlog"
	"jseer/ent/configentry"
	"jseer/ent/configversion"
	"jseer/ent/gmuser"
	"jseer/ent/item"
	"jseer/ent/permission"
	"jseer/ent/pet"
	"jseer/ent/player"
	"jseer/ent/role"
	"jseer/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescEmail is the schema descriptor for email field.
	accountDescEmail := accountFields[0].Descriptor()
	// account.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	account.EmailValidator = accountDescEmail.Validators[0].(func(string) error)
	// accountDescPasswordHash is the schema descriptor for password_hash field.
	accountDescPasswordHash := accountFields[1].Descriptor()
	// account.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	account.PasswordHashValidator = accountDescPasswordHash.Validators[0].(func(string) error)
	// accountDescSalt is the schema descriptor for salt field.
	accountDescSalt := accountFields[2].Descriptor()
	// account.SaltValidator is a validator for the "salt" field. It is called by the builders before save.
	account.SaltValidator = accountDescSalt.Validators[0].(func(string) error)
	// accountDescStatus is the schema descriptor for status field.
	accountDescStatus := accountFields[3].Descriptor()
	// account.DefaultStatus holds the default value on creation for the status field.
	account.DefaultStatus = accountDescStatus.Default.(string)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[4].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[5].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescOperator is the schema descriptor for operator field.
	auditlogDescOperator := auditlogFields[0].Descriptor()
	// auditlog.DefaultOperator holds the default value on creation for the operator field.
	auditlog.DefaultOperator = auditlogDescOperator.Default.(string)
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[1].Descriptor()
	// auditlog.DefaultAction holds the default value on creation for the action field.
	auditlog.DefaultAction = auditlogDescAction.Default.(string)
	// auditlogDescResource is the schema descriptor for resource field.
	auditlogDescResource := auditlogFields[2].Descriptor()
	// auditlog.DefaultResource holds the default value on creation for the resource field.
	auditlog.DefaultResource = auditlogDescResource.Default.(string)
	// auditlogDescResourceID is the schema descriptor for resource_id field.
	auditlogDescResourceID := auditlogFields[3].Descriptor()
	// auditlog.DefaultResourceID holds the default value on creation for the resource_id field.
	auditlog.DefaultResourceID = auditlogDescResourceID.Default.(string)
	// auditlogDescDetail is the schema descriptor for detail field.
	auditlogDescDetail := auditlogFields[4].Descriptor()
	// auditlog.DefaultDetail holds the default value on creation for the detail field.
	auditlog.DefaultDetail = auditlogDescDetail.Default.(string)
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[5].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	configentryFields := schema.ConfigEntry{}.Fields()
	_ = configentryFields
	// configentryDescVersion is the schema descriptor for version field.
	configentryDescVersion := configentryFields[2].Descriptor()
	// configentry.DefaultVersion holds the default value on creation for the version field.
	configentry.DefaultVersion = configentryDescVersion.Default.(int64)
	// configentryDescChecksum is the schema descriptor for checksum field.
	configentryDescChecksum := configentryFields[3].Descriptor()
	// configentry.DefaultChecksum holds the default value on creation for the checksum field.
	configentry.DefaultChecksum = configentryDescChecksum.Default.(string)
	// configentryDescUpdatedAt is the schema descriptor for updated_at field.
	configentryDescUpdatedAt := configentryFields[4].Descriptor()
	// configentry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	configentry.DefaultUpdatedAt = configentryDescUpdatedAt.Default.(func() time.Time)
	// configentry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	configentry.UpdateDefaultUpdatedAt = configentryDescUpdatedAt.UpdateDefault.(func() time.Time)
	configversionFields := schema.ConfigVersion{}.Fields()
	_ = configversionFields
	// configversionDescChecksum is the schema descriptor for checksum field.
	configversionDescChecksum := configversionFields[3].Descriptor()
	// configversion.DefaultChecksum holds the default value on creation for the checksum field.
	configversion.DefaultChecksum = configversionDescChecksum.Default.(string)
	// configversionDescOperator is the schema descriptor for operator field.
	configversionDescOperator := configversionFields[4].Descriptor()
	// configversion.DefaultOperator holds the default value on creation for the operator field.
	configversion.DefaultOperator = configversionDescOperator.Default.(string)
	// configversionDescCreatedAt is the schema descriptor for created_at field.
	configversionDescCreatedAt := configversionFields[5].Descriptor()
	// configversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	configversion.DefaultCreatedAt = configversionDescCreatedAt.Default.(func() time.Time)
	gmuserFields := schema.GMUser{}.Fields()
	_ = gmuserFields
	// gmuserDescPasswordHash is the schema descriptor for password_hash field.
	gmuserDescPasswordHash := gmuserFields[1].Descriptor()
	// gmuser.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	gmuser.PasswordHashValidator = gmuserDescPasswordHash.Validators[0].(func(string) error)
	// gmuserDescStatus is the schema descriptor for status field.
	gmuserDescStatus := gmuserFields[2].Descriptor()
	// gmuser.DefaultStatus holds the default value on creation for the status field.
	gmuser.DefaultStatus = gmuserDescStatus.Default.(string)
	// gmuserDescCreatedAt is the schema descriptor for created_at field.
	gmuserDescCreatedAt := gmuserFields[4].Descriptor()
	// gmuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	gmuser.DefaultCreatedAt = gmuserDescCreatedAt.Default.(func() time.Time)
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescCount is the schema descriptor for count field.
	itemDescCount := itemFields[2].Descriptor()
	// item.DefaultCount holds the default value on creation for the count field.
	item.DefaultCount = itemDescCount.Default.(int)
	// itemDescMeta is the schema descriptor for meta field.
	itemDescMeta := itemFields[3].Descriptor()
	// item.DefaultMeta holds the default value on creation for the meta field.
	item.DefaultMeta = itemDescMeta.Default.(string)
	// itemDescCreatedAt is the schema descriptor for created_at field.
	itemDescCreatedAt := itemFields[4].Descriptor()
	// item.DefaultCreatedAt holds the default value on creation for the created_at field.
	item.DefaultCreatedAt = itemDescCreatedAt.Default.(func() time.Time)
	// itemDescUpdatedAt is the schema descriptor for updated_at field.
	itemDescUpdatedAt := itemFields[5].Descriptor()
	// item.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	item.DefaultUpdatedAt = itemDescUpdatedAt.Default.(func() time.Time)
	// item.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	item.UpdateDefaultUpdatedAt = itemDescUpdatedAt.UpdateDefault.(func() time.Time)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescName is the schema descriptor for name field.
	permissionDescName := permissionFields[1].Descriptor()
	// permission.DefaultName holds the default value on creation for the name field.
	permission.DefaultName = permissionDescName.Default.(string)
	// permissionDescDescription is the schema descriptor for description field.
	permissionDescDescription := permissionFields[2].Descriptor()
	// permission.DefaultDescription holds the default value on creation for the description field.
	permission.DefaultDescription = permissionDescDescription.Default.(string)
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionFields[3].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	petFields := schema.Pet{}.Fields()
	_ = petFields
	// petDescLevel is the schema descriptor for level field.
	petDescLevel := petFields[2].Descriptor()
	// pet.DefaultLevel holds the default value on creation for the level field.
	pet.DefaultLevel = petDescLevel.Default.(int)
	// petDescExp is the schema descriptor for exp field.
	petDescExp := petFields[3].Descriptor()
	// pet.DefaultExp holds the default value on creation for the exp field.
	pet.DefaultExp = petDescExp.Default.(int)
	// petDescHp is the schema descriptor for hp field.
	petDescHp := petFields[4].Descriptor()
	// pet.DefaultHp holds the default value on creation for the hp field.
	pet.DefaultHp = petDescHp.Default.(int)
	// petDescNature is the schema descriptor for nature field.
	petDescNature := petFields[5].Descriptor()
	// pet.DefaultNature holds the default value on creation for the nature field.
	pet.DefaultNature = petDescNature.Default.(string)
	// petDescSkills is the schema descriptor for skills field.
	petDescSkills := petFields[6].Descriptor()
	// pet.DefaultSkills holds the default value on creation for the skills field.
	pet.DefaultSkills = petDescSkills.Default.(string)
	// petDescCreatedAt is the schema descriptor for created_at field.
	petDescCreatedAt := petFields[7].Descriptor()
	// pet.DefaultCreatedAt holds the default value on creation for the created_at field.
	pet.DefaultCreatedAt = petDescCreatedAt.Default.(func() time.Time)
	// petDescUpdatedAt is the schema descriptor for updated_at field.
	petDescUpdatedAt := petFields[8].Descriptor()
	// pet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pet.DefaultUpdatedAt = petDescUpdatedAt.Default.(func() time.Time)
	// pet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pet.UpdateDefaultUpdatedAt = petDescUpdatedAt.UpdateDefault.(func() time.Time)
	playerFields := schema.Player{}.Fields()
	_ = playerFields
	// playerDescNick is the schema descriptor for nick field.
	playerDescNick := playerFields[1].Descriptor()
	// player.NickValidator is a validator for the "nick" field. It is called by the builders before save.
	player.NickValidator = playerDescNick.Validators[0].(func(string) error)
	// playerDescLevel is the schema descriptor for level field.
	playerDescLevel := playerFields[2].Descriptor()
	// player.DefaultLevel holds the default value on creation for the level field.
	player.DefaultLevel = playerDescLevel.Default.(int)
	// playerDescCoins is the schema descriptor for coins field.
	playerDescCoins := playerFields[3].Descriptor()
	// player.DefaultCoins holds the default value on creation for the coins field.
	player.DefaultCoins = playerDescCoins.Default.(int64)
	// playerDescGold is the schema descriptor for gold field.
	playerDescGold := playerFields[4].Descriptor()
	// player.DefaultGold holds the default value on creation for the gold field.
	player.DefaultGold = playerDescGold.Default.(int64)
	// playerDescMapID is the schema descriptor for map_id field.
	playerDescMapID := playerFields[5].Descriptor()
	// player.DefaultMapID holds the default value on creation for the map_id field.
	player.DefaultMapID = playerDescMapID.Default.(int)
	// playerDescPosX is the schema descriptor for pos_x field.
	playerDescPosX := playerFields[6].Descriptor()
	// player.DefaultPosX holds the default value on creation for the pos_x field.
	player.DefaultPosX = playerDescPosX.Default.(int)
	// playerDescPosY is the schema descriptor for pos_y field.
	playerDescPosY := playerFields[7].Descriptor()
	// player.DefaultPosY holds the default value on creation for the pos_y field.
	player.DefaultPosY = playerDescPosY.Default.(int)
	// playerDescCreatedAt is the schema descriptor for created_at field.
	playerDescCreatedAt := playerFields[9].Descriptor()
	// player.DefaultCreatedAt holds the default value on creation for the created_at field.
	player.DefaultCreatedAt = playerDescCreatedAt.Default.(func() time.Time)
	// playerDescUpdatedAt is the schema descriptor for updated_at field.
	playerDescUpdatedAt := playerFields[10].Descriptor()
	// player.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	player.DefaultUpdatedAt = playerDescUpdatedAt.Default.(func() time.Time)
	// player.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	player.UpdateDefaultUpdatedAt = playerDescUpdatedAt.UpdateDefault.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[1].Descriptor()
	// role.DefaultDescription holds the default value on creation for the description field.
	role.DefaultDescription = roleDescDescription.Default.(string)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[2].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
}
