// Code generated by ent, DO NOT EDIT.

package player

import (
	"jseer/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldAccountID, v))
}

// Nick applies equality check predicate on the "nick" field. It's identical to NickEQ.
func Nick(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldNick, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLevel, v))
}

// Coins applies equality check predicate on the "coins" field. It's identical to CoinsEQ.
func Coins(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCoins, v))
}

// Gold applies equality check predicate on the "gold" field. It's identical to GoldEQ.
func Gold(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldGold, v))
}

// MapID applies equality check predicate on the "map_id" field. It's identical to MapIDEQ.
func MapID(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldMapID, v))
}

// MapType applies equality check predicate on the "map_type" field. It's identical to MapTypeEQ.
func MapType(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldMapType, v))
}

// PosX applies equality check predicate on the "pos_x" field. It's identical to PosXEQ.
func PosX(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldPosX, v))
}

// PosY applies equality check predicate on the "pos_y" field. It's identical to PosYEQ.
func PosY(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldPosY, v))
}

// LastMapID applies equality check predicate on the "last_map_id" field. It's identical to LastMapIDEQ.
func LastMapID(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLastMapID, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldColor, v))
}

// Texture applies equality check predicate on the "texture" field. It's identical to TextureEQ.
func Texture(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTexture, v))
}

// Energy applies equality check predicate on the "energy" field. It's identical to EnergyEQ.
func Energy(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldEnergy, v))
}

// FightBadge applies equality check predicate on the "fight_badge" field. It's identical to FightBadgeEQ.
func FightBadge(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldFightBadge, v))
}

// TimeToday applies equality check predicate on the "time_today" field. It's identical to TimeTodayEQ.
func TimeToday(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTimeToday, v))
}

// TimeLimit applies equality check predicate on the "time_limit" field. It's identical to TimeLimitEQ.
func TimeLimit(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTimeLimit, v))
}

// TeacherID applies equality check predicate on the "teacher_id" field. It's identical to TeacherIDEQ.
func TeacherID(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTeacherID, v))
}

// StudentID applies equality check predicate on the "student_id" field. It's identical to StudentIDEQ.
func StudentID(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldStudentID, v))
}

// CurTitle applies equality check predicate on the "cur_title" field. It's identical to CurTitleEQ.
func CurTitle(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCurTitle, v))
}

// TaskStatus applies equality check predicate on the "task_status" field. It's identical to TaskStatusEQ.
func TaskStatus(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTaskStatus, v))
}

// TaskBufs applies equality check predicate on the "task_bufs" field. It's identical to TaskBufsEQ.
func TaskBufs(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTaskBufs, v))
}

// CurrentPetID applies equality check predicate on the "current_pet_id" field. It's identical to CurrentPetIDEQ.
func CurrentPetID(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCurrentPetID, v))
}

// CurrentPetCatchTime applies equality check predicate on the "current_pet_catch_time" field. It's identical to CurrentPetCatchTimeEQ.
func CurrentPetCatchTime(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCurrentPetCatchTime, v))
}

// CurrentPetDv applies equality check predicate on the "current_pet_dv" field. It's identical to CurrentPetDvEQ.
func CurrentPetDv(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCurrentPetDv, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLastLoginAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldAccountID, vs...))
}

// NickEQ applies the EQ predicate on the "nick" field.
func NickEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldNick, v))
}

// NickNEQ applies the NEQ predicate on the "nick" field.
func NickNEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldNick, v))
}

// NickIn applies the In predicate on the "nick" field.
func NickIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldNick, vs...))
}

// NickNotIn applies the NotIn predicate on the "nick" field.
func NickNotIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldNick, vs...))
}

// NickGT applies the GT predicate on the "nick" field.
func NickGT(v string) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldNick, v))
}

// NickGTE applies the GTE predicate on the "nick" field.
func NickGTE(v string) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldNick, v))
}

// NickLT applies the LT predicate on the "nick" field.
func NickLT(v string) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldNick, v))
}

// NickLTE applies the LTE predicate on the "nick" field.
func NickLTE(v string) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldNick, v))
}

// NickContains applies the Contains predicate on the "nick" field.
func NickContains(v string) predicate.Player {
	return predicate.Player(sql.FieldContains(FieldNick, v))
}

// NickHasPrefix applies the HasPrefix predicate on the "nick" field.
func NickHasPrefix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasPrefix(FieldNick, v))
}

// NickHasSuffix applies the HasSuffix predicate on the "nick" field.
func NickHasSuffix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasSuffix(FieldNick, v))
}

// NickEqualFold applies the EqualFold predicate on the "nick" field.
func NickEqualFold(v string) predicate.Player {
	return predicate.Player(sql.FieldEqualFold(FieldNick, v))
}

// NickContainsFold applies the ContainsFold predicate on the "nick" field.
func NickContainsFold(v string) predicate.Player {
	return predicate.Player(sql.FieldContainsFold(FieldNick, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldLevel, v))
}

// CoinsEQ applies the EQ predicate on the "coins" field.
func CoinsEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCoins, v))
}

// CoinsNEQ applies the NEQ predicate on the "coins" field.
func CoinsNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldCoins, v))
}

// CoinsIn applies the In predicate on the "coins" field.
func CoinsIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldCoins, vs...))
}

// CoinsNotIn applies the NotIn predicate on the "coins" field.
func CoinsNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldCoins, vs...))
}

// CoinsGT applies the GT predicate on the "coins" field.
func CoinsGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldCoins, v))
}

// CoinsGTE applies the GTE predicate on the "coins" field.
func CoinsGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldCoins, v))
}

// CoinsLT applies the LT predicate on the "coins" field.
func CoinsLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldCoins, v))
}

// CoinsLTE applies the LTE predicate on the "coins" field.
func CoinsLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldCoins, v))
}

// GoldEQ applies the EQ predicate on the "gold" field.
func GoldEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldGold, v))
}

// GoldNEQ applies the NEQ predicate on the "gold" field.
func GoldNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldGold, v))
}

// GoldIn applies the In predicate on the "gold" field.
func GoldIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldGold, vs...))
}

// GoldNotIn applies the NotIn predicate on the "gold" field.
func GoldNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldGold, vs...))
}

// GoldGT applies the GT predicate on the "gold" field.
func GoldGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldGold, v))
}

// GoldGTE applies the GTE predicate on the "gold" field.
func GoldGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldGold, v))
}

// GoldLT applies the LT predicate on the "gold" field.
func GoldLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldGold, v))
}

// GoldLTE applies the LTE predicate on the "gold" field.
func GoldLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldGold, v))
}

// MapIDEQ applies the EQ predicate on the "map_id" field.
func MapIDEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldMapID, v))
}

// MapIDNEQ applies the NEQ predicate on the "map_id" field.
func MapIDNEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldMapID, v))
}

// MapIDIn applies the In predicate on the "map_id" field.
func MapIDIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldMapID, vs...))
}

// MapIDNotIn applies the NotIn predicate on the "map_id" field.
func MapIDNotIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldMapID, vs...))
}

// MapIDGT applies the GT predicate on the "map_id" field.
func MapIDGT(v int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldMapID, v))
}

// MapIDGTE applies the GTE predicate on the "map_id" field.
func MapIDGTE(v int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldMapID, v))
}

// MapIDLT applies the LT predicate on the "map_id" field.
func MapIDLT(v int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldMapID, v))
}

// MapIDLTE applies the LTE predicate on the "map_id" field.
func MapIDLTE(v int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldMapID, v))
}

// MapTypeEQ applies the EQ predicate on the "map_type" field.
func MapTypeEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldMapType, v))
}

// MapTypeNEQ applies the NEQ predicate on the "map_type" field.
func MapTypeNEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldMapType, v))
}

// MapTypeIn applies the In predicate on the "map_type" field.
func MapTypeIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldMapType, vs...))
}

// MapTypeNotIn applies the NotIn predicate on the "map_type" field.
func MapTypeNotIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldMapType, vs...))
}

// MapTypeGT applies the GT predicate on the "map_type" field.
func MapTypeGT(v int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldMapType, v))
}

// MapTypeGTE applies the GTE predicate on the "map_type" field.
func MapTypeGTE(v int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldMapType, v))
}

// MapTypeLT applies the LT predicate on the "map_type" field.
func MapTypeLT(v int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldMapType, v))
}

// MapTypeLTE applies the LTE predicate on the "map_type" field.
func MapTypeLTE(v int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldMapType, v))
}

// PosXEQ applies the EQ predicate on the "pos_x" field.
func PosXEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldPosX, v))
}

// PosXNEQ applies the NEQ predicate on the "pos_x" field.
func PosXNEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldPosX, v))
}

// PosXIn applies the In predicate on the "pos_x" field.
func PosXIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldPosX, vs...))
}

// PosXNotIn applies the NotIn predicate on the "pos_x" field.
func PosXNotIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldPosX, vs...))
}

// PosXGT applies the GT predicate on the "pos_x" field.
func PosXGT(v int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldPosX, v))
}

// PosXGTE applies the GTE predicate on the "pos_x" field.
func PosXGTE(v int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldPosX, v))
}

// PosXLT applies the LT predicate on the "pos_x" field.
func PosXLT(v int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldPosX, v))
}

// PosXLTE applies the LTE predicate on the "pos_x" field.
func PosXLTE(v int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldPosX, v))
}

// PosYEQ applies the EQ predicate on the "pos_y" field.
func PosYEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldPosY, v))
}

// PosYNEQ applies the NEQ predicate on the "pos_y" field.
func PosYNEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldPosY, v))
}

// PosYIn applies the In predicate on the "pos_y" field.
func PosYIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldPosY, vs...))
}

// PosYNotIn applies the NotIn predicate on the "pos_y" field.
func PosYNotIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldPosY, vs...))
}

// PosYGT applies the GT predicate on the "pos_y" field.
func PosYGT(v int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldPosY, v))
}

// PosYGTE applies the GTE predicate on the "pos_y" field.
func PosYGTE(v int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldPosY, v))
}

// PosYLT applies the LT predicate on the "pos_y" field.
func PosYLT(v int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldPosY, v))
}

// PosYLTE applies the LTE predicate on the "pos_y" field.
func PosYLTE(v int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldPosY, v))
}

// LastMapIDEQ applies the EQ predicate on the "last_map_id" field.
func LastMapIDEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLastMapID, v))
}

// LastMapIDNEQ applies the NEQ predicate on the "last_map_id" field.
func LastMapIDNEQ(v int) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldLastMapID, v))
}

// LastMapIDIn applies the In predicate on the "last_map_id" field.
func LastMapIDIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldLastMapID, vs...))
}

// LastMapIDNotIn applies the NotIn predicate on the "last_map_id" field.
func LastMapIDNotIn(vs ...int) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldLastMapID, vs...))
}

// LastMapIDGT applies the GT predicate on the "last_map_id" field.
func LastMapIDGT(v int) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldLastMapID, v))
}

// LastMapIDGTE applies the GTE predicate on the "last_map_id" field.
func LastMapIDGTE(v int) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldLastMapID, v))
}

// LastMapIDLT applies the LT predicate on the "last_map_id" field.
func LastMapIDLT(v int) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldLastMapID, v))
}

// LastMapIDLTE applies the LTE predicate on the "last_map_id" field.
func LastMapIDLTE(v int) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldLastMapID, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldColor, v))
}

// TextureEQ applies the EQ predicate on the "texture" field.
func TextureEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTexture, v))
}

// TextureNEQ applies the NEQ predicate on the "texture" field.
func TextureNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldTexture, v))
}

// TextureIn applies the In predicate on the "texture" field.
func TextureIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldTexture, vs...))
}

// TextureNotIn applies the NotIn predicate on the "texture" field.
func TextureNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldTexture, vs...))
}

// TextureGT applies the GT predicate on the "texture" field.
func TextureGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldTexture, v))
}

// TextureGTE applies the GTE predicate on the "texture" field.
func TextureGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldTexture, v))
}

// TextureLT applies the LT predicate on the "texture" field.
func TextureLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldTexture, v))
}

// TextureLTE applies the LTE predicate on the "texture" field.
func TextureLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldTexture, v))
}

// EnergyEQ applies the EQ predicate on the "energy" field.
func EnergyEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldEnergy, v))
}

// EnergyNEQ applies the NEQ predicate on the "energy" field.
func EnergyNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldEnergy, v))
}

// EnergyIn applies the In predicate on the "energy" field.
func EnergyIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldEnergy, vs...))
}

// EnergyNotIn applies the NotIn predicate on the "energy" field.
func EnergyNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldEnergy, vs...))
}

// EnergyGT applies the GT predicate on the "energy" field.
func EnergyGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldEnergy, v))
}

// EnergyGTE applies the GTE predicate on the "energy" field.
func EnergyGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldEnergy, v))
}

// EnergyLT applies the LT predicate on the "energy" field.
func EnergyLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldEnergy, v))
}

// EnergyLTE applies the LTE predicate on the "energy" field.
func EnergyLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldEnergy, v))
}

// FightBadgeEQ applies the EQ predicate on the "fight_badge" field.
func FightBadgeEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldFightBadge, v))
}

// FightBadgeNEQ applies the NEQ predicate on the "fight_badge" field.
func FightBadgeNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldFightBadge, v))
}

// FightBadgeIn applies the In predicate on the "fight_badge" field.
func FightBadgeIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldFightBadge, vs...))
}

// FightBadgeNotIn applies the NotIn predicate on the "fight_badge" field.
func FightBadgeNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldFightBadge, vs...))
}

// FightBadgeGT applies the GT predicate on the "fight_badge" field.
func FightBadgeGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldFightBadge, v))
}

// FightBadgeGTE applies the GTE predicate on the "fight_badge" field.
func FightBadgeGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldFightBadge, v))
}

// FightBadgeLT applies the LT predicate on the "fight_badge" field.
func FightBadgeLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldFightBadge, v))
}

// FightBadgeLTE applies the LTE predicate on the "fight_badge" field.
func FightBadgeLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldFightBadge, v))
}

// TimeTodayEQ applies the EQ predicate on the "time_today" field.
func TimeTodayEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTimeToday, v))
}

// TimeTodayNEQ applies the NEQ predicate on the "time_today" field.
func TimeTodayNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldTimeToday, v))
}

// TimeTodayIn applies the In predicate on the "time_today" field.
func TimeTodayIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldTimeToday, vs...))
}

// TimeTodayNotIn applies the NotIn predicate on the "time_today" field.
func TimeTodayNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldTimeToday, vs...))
}

// TimeTodayGT applies the GT predicate on the "time_today" field.
func TimeTodayGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldTimeToday, v))
}

// TimeTodayGTE applies the GTE predicate on the "time_today" field.
func TimeTodayGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldTimeToday, v))
}

// TimeTodayLT applies the LT predicate on the "time_today" field.
func TimeTodayLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldTimeToday, v))
}

// TimeTodayLTE applies the LTE predicate on the "time_today" field.
func TimeTodayLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldTimeToday, v))
}

// TimeLimitEQ applies the EQ predicate on the "time_limit" field.
func TimeLimitEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTimeLimit, v))
}

// TimeLimitNEQ applies the NEQ predicate on the "time_limit" field.
func TimeLimitNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldTimeLimit, v))
}

// TimeLimitIn applies the In predicate on the "time_limit" field.
func TimeLimitIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldTimeLimit, vs...))
}

// TimeLimitNotIn applies the NotIn predicate on the "time_limit" field.
func TimeLimitNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldTimeLimit, vs...))
}

// TimeLimitGT applies the GT predicate on the "time_limit" field.
func TimeLimitGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldTimeLimit, v))
}

// TimeLimitGTE applies the GTE predicate on the "time_limit" field.
func TimeLimitGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldTimeLimit, v))
}

// TimeLimitLT applies the LT predicate on the "time_limit" field.
func TimeLimitLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldTimeLimit, v))
}

// TimeLimitLTE applies the LTE predicate on the "time_limit" field.
func TimeLimitLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldTimeLimit, v))
}

// TeacherIDEQ applies the EQ predicate on the "teacher_id" field.
func TeacherIDEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTeacherID, v))
}

// TeacherIDNEQ applies the NEQ predicate on the "teacher_id" field.
func TeacherIDNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldTeacherID, v))
}

// TeacherIDIn applies the In predicate on the "teacher_id" field.
func TeacherIDIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldTeacherID, vs...))
}

// TeacherIDNotIn applies the NotIn predicate on the "teacher_id" field.
func TeacherIDNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldTeacherID, vs...))
}

// TeacherIDGT applies the GT predicate on the "teacher_id" field.
func TeacherIDGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldTeacherID, v))
}

// TeacherIDGTE applies the GTE predicate on the "teacher_id" field.
func TeacherIDGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldTeacherID, v))
}

// TeacherIDLT applies the LT predicate on the "teacher_id" field.
func TeacherIDLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldTeacherID, v))
}

// TeacherIDLTE applies the LTE predicate on the "teacher_id" field.
func TeacherIDLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldTeacherID, v))
}

// StudentIDEQ applies the EQ predicate on the "student_id" field.
func StudentIDEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldStudentID, v))
}

// StudentIDNEQ applies the NEQ predicate on the "student_id" field.
func StudentIDNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldStudentID, v))
}

// StudentIDIn applies the In predicate on the "student_id" field.
func StudentIDIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldStudentID, vs...))
}

// StudentIDNotIn applies the NotIn predicate on the "student_id" field.
func StudentIDNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldStudentID, vs...))
}

// StudentIDGT applies the GT predicate on the "student_id" field.
func StudentIDGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldStudentID, v))
}

// StudentIDGTE applies the GTE predicate on the "student_id" field.
func StudentIDGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldStudentID, v))
}

// StudentIDLT applies the LT predicate on the "student_id" field.
func StudentIDLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldStudentID, v))
}

// StudentIDLTE applies the LTE predicate on the "student_id" field.
func StudentIDLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldStudentID, v))
}

// CurTitleEQ applies the EQ predicate on the "cur_title" field.
func CurTitleEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCurTitle, v))
}

// CurTitleNEQ applies the NEQ predicate on the "cur_title" field.
func CurTitleNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldCurTitle, v))
}

// CurTitleIn applies the In predicate on the "cur_title" field.
func CurTitleIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldCurTitle, vs...))
}

// CurTitleNotIn applies the NotIn predicate on the "cur_title" field.
func CurTitleNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldCurTitle, vs...))
}

// CurTitleGT applies the GT predicate on the "cur_title" field.
func CurTitleGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldCurTitle, v))
}

// CurTitleGTE applies the GTE predicate on the "cur_title" field.
func CurTitleGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldCurTitle, v))
}

// CurTitleLT applies the LT predicate on the "cur_title" field.
func CurTitleLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldCurTitle, v))
}

// CurTitleLTE applies the LTE predicate on the "cur_title" field.
func CurTitleLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldCurTitle, v))
}

// TaskStatusEQ applies the EQ predicate on the "task_status" field.
func TaskStatusEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTaskStatus, v))
}

// TaskStatusNEQ applies the NEQ predicate on the "task_status" field.
func TaskStatusNEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldTaskStatus, v))
}

// TaskStatusIn applies the In predicate on the "task_status" field.
func TaskStatusIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldTaskStatus, vs...))
}

// TaskStatusNotIn applies the NotIn predicate on the "task_status" field.
func TaskStatusNotIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldTaskStatus, vs...))
}

// TaskStatusGT applies the GT predicate on the "task_status" field.
func TaskStatusGT(v string) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldTaskStatus, v))
}

// TaskStatusGTE applies the GTE predicate on the "task_status" field.
func TaskStatusGTE(v string) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldTaskStatus, v))
}

// TaskStatusLT applies the LT predicate on the "task_status" field.
func TaskStatusLT(v string) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldTaskStatus, v))
}

// TaskStatusLTE applies the LTE predicate on the "task_status" field.
func TaskStatusLTE(v string) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldTaskStatus, v))
}

// TaskStatusContains applies the Contains predicate on the "task_status" field.
func TaskStatusContains(v string) predicate.Player {
	return predicate.Player(sql.FieldContains(FieldTaskStatus, v))
}

// TaskStatusHasPrefix applies the HasPrefix predicate on the "task_status" field.
func TaskStatusHasPrefix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasPrefix(FieldTaskStatus, v))
}

// TaskStatusHasSuffix applies the HasSuffix predicate on the "task_status" field.
func TaskStatusHasSuffix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasSuffix(FieldTaskStatus, v))
}

// TaskStatusEqualFold applies the EqualFold predicate on the "task_status" field.
func TaskStatusEqualFold(v string) predicate.Player {
	return predicate.Player(sql.FieldEqualFold(FieldTaskStatus, v))
}

// TaskStatusContainsFold applies the ContainsFold predicate on the "task_status" field.
func TaskStatusContainsFold(v string) predicate.Player {
	return predicate.Player(sql.FieldContainsFold(FieldTaskStatus, v))
}

// TaskBufsEQ applies the EQ predicate on the "task_bufs" field.
func TaskBufsEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldTaskBufs, v))
}

// TaskBufsNEQ applies the NEQ predicate on the "task_bufs" field.
func TaskBufsNEQ(v string) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldTaskBufs, v))
}

// TaskBufsIn applies the In predicate on the "task_bufs" field.
func TaskBufsIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldTaskBufs, vs...))
}

// TaskBufsNotIn applies the NotIn predicate on the "task_bufs" field.
func TaskBufsNotIn(vs ...string) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldTaskBufs, vs...))
}

// TaskBufsGT applies the GT predicate on the "task_bufs" field.
func TaskBufsGT(v string) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldTaskBufs, v))
}

// TaskBufsGTE applies the GTE predicate on the "task_bufs" field.
func TaskBufsGTE(v string) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldTaskBufs, v))
}

// TaskBufsLT applies the LT predicate on the "task_bufs" field.
func TaskBufsLT(v string) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldTaskBufs, v))
}

// TaskBufsLTE applies the LTE predicate on the "task_bufs" field.
func TaskBufsLTE(v string) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldTaskBufs, v))
}

// TaskBufsContains applies the Contains predicate on the "task_bufs" field.
func TaskBufsContains(v string) predicate.Player {
	return predicate.Player(sql.FieldContains(FieldTaskBufs, v))
}

// TaskBufsHasPrefix applies the HasPrefix predicate on the "task_bufs" field.
func TaskBufsHasPrefix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasPrefix(FieldTaskBufs, v))
}

// TaskBufsHasSuffix applies the HasSuffix predicate on the "task_bufs" field.
func TaskBufsHasSuffix(v string) predicate.Player {
	return predicate.Player(sql.FieldHasSuffix(FieldTaskBufs, v))
}

// TaskBufsEqualFold applies the EqualFold predicate on the "task_bufs" field.
func TaskBufsEqualFold(v string) predicate.Player {
	return predicate.Player(sql.FieldEqualFold(FieldTaskBufs, v))
}

// TaskBufsContainsFold applies the ContainsFold predicate on the "task_bufs" field.
func TaskBufsContainsFold(v string) predicate.Player {
	return predicate.Player(sql.FieldContainsFold(FieldTaskBufs, v))
}

// CurrentPetIDEQ applies the EQ predicate on the "current_pet_id" field.
func CurrentPetIDEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCurrentPetID, v))
}

// CurrentPetIDNEQ applies the NEQ predicate on the "current_pet_id" field.
func CurrentPetIDNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldCurrentPetID, v))
}

// CurrentPetIDIn applies the In predicate on the "current_pet_id" field.
func CurrentPetIDIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldCurrentPetID, vs...))
}

// CurrentPetIDNotIn applies the NotIn predicate on the "current_pet_id" field.
func CurrentPetIDNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldCurrentPetID, vs...))
}

// CurrentPetIDGT applies the GT predicate on the "current_pet_id" field.
func CurrentPetIDGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldCurrentPetID, v))
}

// CurrentPetIDGTE applies the GTE predicate on the "current_pet_id" field.
func CurrentPetIDGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldCurrentPetID, v))
}

// CurrentPetIDLT applies the LT predicate on the "current_pet_id" field.
func CurrentPetIDLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldCurrentPetID, v))
}

// CurrentPetIDLTE applies the LTE predicate on the "current_pet_id" field.
func CurrentPetIDLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldCurrentPetID, v))
}

// CurrentPetCatchTimeEQ applies the EQ predicate on the "current_pet_catch_time" field.
func CurrentPetCatchTimeEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCurrentPetCatchTime, v))
}

// CurrentPetCatchTimeNEQ applies the NEQ predicate on the "current_pet_catch_time" field.
func CurrentPetCatchTimeNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldCurrentPetCatchTime, v))
}

// CurrentPetCatchTimeIn applies the In predicate on the "current_pet_catch_time" field.
func CurrentPetCatchTimeIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldCurrentPetCatchTime, vs...))
}

// CurrentPetCatchTimeNotIn applies the NotIn predicate on the "current_pet_catch_time" field.
func CurrentPetCatchTimeNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldCurrentPetCatchTime, vs...))
}

// CurrentPetCatchTimeGT applies the GT predicate on the "current_pet_catch_time" field.
func CurrentPetCatchTimeGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldCurrentPetCatchTime, v))
}

// CurrentPetCatchTimeGTE applies the GTE predicate on the "current_pet_catch_time" field.
func CurrentPetCatchTimeGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldCurrentPetCatchTime, v))
}

// CurrentPetCatchTimeLT applies the LT predicate on the "current_pet_catch_time" field.
func CurrentPetCatchTimeLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldCurrentPetCatchTime, v))
}

// CurrentPetCatchTimeLTE applies the LTE predicate on the "current_pet_catch_time" field.
func CurrentPetCatchTimeLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldCurrentPetCatchTime, v))
}

// CurrentPetDvEQ applies the EQ predicate on the "current_pet_dv" field.
func CurrentPetDvEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCurrentPetDv, v))
}

// CurrentPetDvNEQ applies the NEQ predicate on the "current_pet_dv" field.
func CurrentPetDvNEQ(v int64) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldCurrentPetDv, v))
}

// CurrentPetDvIn applies the In predicate on the "current_pet_dv" field.
func CurrentPetDvIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldCurrentPetDv, vs...))
}

// CurrentPetDvNotIn applies the NotIn predicate on the "current_pet_dv" field.
func CurrentPetDvNotIn(vs ...int64) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldCurrentPetDv, vs...))
}

// CurrentPetDvGT applies the GT predicate on the "current_pet_dv" field.
func CurrentPetDvGT(v int64) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldCurrentPetDv, v))
}

// CurrentPetDvGTE applies the GTE predicate on the "current_pet_dv" field.
func CurrentPetDvGTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldCurrentPetDv, v))
}

// CurrentPetDvLT applies the LT predicate on the "current_pet_dv" field.
func CurrentPetDvLT(v int64) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldCurrentPetDv, v))
}

// CurrentPetDvLTE applies the LTE predicate on the "current_pet_dv" field.
func CurrentPetDvLTE(v int64) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldCurrentPetDv, v))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldLastLoginAt, v))
}

// LastLoginAtIsNil applies the IsNil predicate on the "last_login_at" field.
func LastLoginAtIsNil() predicate.Player {
	return predicate.Player(sql.FieldIsNull(FieldLastLoginAt))
}

// LastLoginAtNotNil applies the NotNil predicate on the "last_login_at" field.
func LastLoginAtNotNil() predicate.Player {
	return predicate.Player(sql.FieldNotNull(FieldLastLoginAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Player {
	return predicate.Player(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Player {
	return predicate.Player(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.Player {
	return predicate.Player(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.Player {
	return predicate.Player(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPets applies the HasEdge predicate on the "pets" edge.
func HasPets() predicate.Player {
	return predicate.Player(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PetsTable, PetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPetsWith applies the HasEdge predicate on the "pets" edge with a given conditions (other predicates).
func HasPetsWith(preds ...predicate.Pet) predicate.Player {
	return predicate.Player(func(s *sql.Selector) {
		step := newPetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.Player {
	return predicate.Player(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.Item) predicate.Player {
	return predicate.Player(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Player) predicate.Player {
	return predicate.Player(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Player) predicate.Player {
	return predicate.Player(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Player) predicate.Player {
	return predicate.Player(sql.NotPredicates(p))
}
