// Code generated by ent, DO NOT EDIT.

package configversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the configversion type in the database.
	Label = "config_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldChecksum holds the string denoting the checksum field in the database.
	FieldChecksum = "checksum"
	// FieldOperator holds the string denoting the operator field in the database.
	FieldOperator = "operator"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeEntry holds the string denoting the entry edge name in mutations.
	EdgeEntry = "entry"
	// Table holds the table name of the configversion in the database.
	Table = "config_versions"
	// EntryTable is the table that holds the entry relation/edge.
	EntryTable = "config_versions"
	// EntryInverseTable is the table name for the ConfigEntry entity.
	// It exists in this package in order to avoid circular dependency with the "configentry" package.
	EntryInverseTable = "config_entries"
	// EntryColumn is the table column denoting the entry relation/edge.
	EntryColumn = "config_entry_versions"
)

// Columns holds all SQL columns for configversion fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldVersion,
	FieldValue,
	FieldChecksum,
	FieldOperator,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "config_versions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"config_entry_versions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultChecksum holds the default value on creation for the "checksum" field.
	DefaultChecksum string
	// DefaultOperator holds the default value on creation for the "operator" field.
	DefaultOperator string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ConfigVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByChecksum orders the results by the checksum field.
func ByChecksum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChecksum, opts...).ToFunc()
}

// ByOperator orders the results by the operator field.
func ByOperator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperator, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByEntryField orders the results by entry field.
func ByEntryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntryStep(), sql.OrderByField(field, opts...))
	}
}
func newEntryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EntryTable, EntryColumn),
	)
}
