// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// ConfigEntry is the predicate function for configentry builders.
type ConfigEntry func(*sql.Selector)

// ConfigVersion is the predicate function for configversion builders.
type ConfigVersion func(*sql.Selector)

// GMUser is the predicate function for gmuser builders.
type GMUser func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Pet is the predicate function for pet builders.
type Pet func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)
